import { api, clearCache } from './control-center-api.js';

export const DOMAIN_META = Object.freeze({
  hq: { title: 'HQ', kicker: 'Corporate Operations', context: 'What matters, what moved, and what needs you.' },
  work: { title: 'Work', kicker: 'Master Checklist', context: 'The live source of truth for Pitmark work.' },
  prt: { title: 'PRT', kicker: 'Product Operations', context: 'Testers, feedback, Founder’s Race, and product work.' },
  partnerships: { title: 'Partnerships', kicker: 'Relationships', context: 'Tracks, leagues, broadcasters, partners, and follow-ups.' },
  content: { title: 'Content', kicker: 'Social Manager', context: 'Generated posts, approvals, publishing, and editorial.' },
  store: { title: 'Store & Brand', kicker: 'Commerce Operations', context: 'Store, web, brand, launches, and related work.' },
  people: { title: 'People', kicker: 'Pitmark Network', context: 'The people and organizations moving Pitmark forward.' },
  systems: { title: 'Systems', kicker: 'Platform Operations', context: 'Pitmark Cloud, automation, services, and signals.' },
  insights: { title: 'Insights', kicker: 'Operating Intelligence', context: 'Useful momentum from real Pitmark activity.' },
});

const esc = (value = '') => String(value ?? '').replace(/[&<>'"]/g, ch => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[ch]));
const n = (value) => Number(value || 0).toLocaleString();
const low = (value) => String(value || '').trim().toLowerCase();
const compact = (value, max = 120) => { const s = String(value || '').replace(/\s+/g, ' ').trim(); return s.length > max ? `${s.slice(0, max - 1)}…` : s; };
const dateText = (value) => {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toLocaleString([], { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' });
};
const age = (value) => {
  if (!value) return 'unknown age';
  const d = new Date(value); if (Number.isNaN(d.getTime())) return String(value);
  const seconds = Math.max(0, (Date.now() - d.getTime()) / 1000);
  if (seconds < 90) return 'just now';
  if (seconds < 3600) return `${Math.floor(seconds/60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds/3600)}h ago`;
  return `${Math.floor(seconds/86400)}d ago`;
};
const titleOf = (row, fallback = 'Untitled') => row?.name || row?.full_name || row?.tester_name || row?.display_name || row?.organization || row?.title || row?.email || fallback;
const statusBadge = (status = 'unknown') => {
  const s = low(status); const tone = ['done','complete','completed','published','redeemed','active','accepted','resolved'].includes(s) ? 'good' : ['blocked','declined','rejected','expired','revoked','error','failed'].includes(s) ? 'bad' : ['waiting','monitoring','hold','scheduled','issued','reviewing','pending'].includes(s) ? 'warn' : '';
  return `<span class="pm-badge ${tone}">${esc(status || 'unknown')}</span>`;
};
const priority = (value = '') => `<span class="pm-priority ${esc(low(value))}">${esc(value || '—')}</span>`;
const moduleError = (name, error, retry = '') => `<div class="pm-callout is-error"><span class="icon">!</span><div><strong>${esc(name)} could not load</strong><p>${esc(error || 'Pitmark Cloud returned an unavailable state.')}</p>${retry ? `<div class="pm-error-actions"><button class="pm-button pm-button-ghost" data-retry="${esc(retry)}">Retry</button></div>` : ''}</div></div>`;
const empty = (text) => `<div class="pm-empty">${esc(text)}</div>`;
const viewHeader = (eyebrow, title, copy, actions = '') => `<header class="pm-view-header"><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><div class="pm-view-actions">${actions}</div></header>`;
const panel = (title, eyebrow, body, tools = '') => `<section class="pm-surface pm-panel"><header class="pm-panel-header"><div><span class="eyebrow">${esc(eyebrow)}</span><h3>${esc(title)}</h3></div><div class="pm-panel-tools">${tools}</div></header>${body}</section>`;
const details = (pairs) => `<div class="pm-detail-list">${pairs.filter(([,v]) => v !== undefined && v !== null && v !== '').map(([k,v]) => `<div class="pm-detail-pair"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`;
const workRow = (item) => `<button class="pm-row" type="button" data-open-work="${Number(item.row_number)}"><div class="pm-row-main"><div class="pm-row-meta">${priority(item.priority)}<span class="pm-status ${esc(item.bucket)}">${esc(item.status || item.bucket)}</span><span class="pm-badge">${esc(item.area || 'General')}</span></div><strong>${esc(item.task || 'Untitled work')}</strong><p>${esc(compact(item.next_action || item.notes || 'No next action recorded.', 150))}</p></div><div class="pm-row-side"><span class="pm-muted">${esc(item.last_updated || 'No date')}</span><span>›</span></div></button>`;

function unwrap(module) { return module?.ok ? module.data : null; }
function failure(module, fallback) { return module?.ok === false ? module.error : fallback; }

async function renderHQ(root, ctx) {
  const payload = await api.hq({ maxAge: ctx.force ? 0 : 15000 });
  const modules = payload?.modules || {};
  const workConnected = modules.work?.ok === true;
  const work = unwrap(modules.work); const prt = unwrap(modules.prt); const content = unwrap(modules.content); const relationships = unwrap(modules.relationships); const systems = unwrap(modules.systems); const notifications = unwrap(modules.notifications);
  const attention = work?.attention || [];
  const wait = work?.waiting || [];
  const summary = work?.summary || {};
  const p = prt || {}; const c = content || {};
  const headline = workConnected ? (attention.length ? `${attention.length} thing${attention.length === 1 ? '' : 's'} deserve your attention.` : 'Pitmark is clear for the moment.') : 'Pitmark HQ is online.';
  const sub = workConnected ? (work?.stale ? 'Master Checklist is showing cached data while the live source reconnects.' : 'Live operations across work, PRT, content, relationships, and systems.') : 'PRT, content, relationships, and systems are live. Work sync is temporarily unavailable.';
  const checklistBadge = workConnected ? (work?.stale ? '<span class="pm-badge warn">Checklist cached</span>' : '<span class="pm-badge good">Checklist live</span>') : '<span class="pm-badge warn">Checklist unavailable</span>';
  const hqGridClass = workConnected ? 'pm-grid pm-grid-hq' : 'pm-grid';
  root.innerHTML = `
    <section class="pm-brief"><div><span class="eyebrow">TODAY AT PITMARK</span><h2>${esc(headline)}</h2><p>${esc(sub)}</p></div><div class="pm-brief-meta">${checklistBadge}<span class="pm-badge">v${esc(payload?.version || systems?.app_version || '—')}</span></div></section>
    <div class="pm-metric-strip">
      ${workConnected ? `<div class="pm-metric"><span>Needs attention</span><strong>${n(attention.length)}</strong><small>P0/P1, blockers, active work</small></div><div class="pm-metric"><span>Waiting</span><strong>${n(summary.waiting)}</strong><small>External or pending items</small></div>` : ''}
      <div class="pm-metric"><span>PRT applications</span><strong>${n(p.applications?.new)}</strong><small>New applications</small></div>
      <div class="pm-metric"><span>Content approvals</span><strong>${n(c.autopilot?.pending)}</strong><small>Generated posts waiting</small></div>
      <div class="pm-metric"><span>Relationships</span><strong>${n(relationships?.total)}</strong><small>${n(relationships?.waiting_follow_up)} follow-ups tracked</small></div>
      ${workConnected ? '' : `<div class="pm-metric"><span>PRT feedback</span><strong>${n(p.feedback?.open ?? p.feedback?.total ?? 0)}</strong><small>Open tester feedback</small></div><div class="pm-metric"><span>Signals</span><strong>${n(notifications?.unread)}</strong><small>Unread operational signals</small></div>`}
    </div>
    <div class="${hqGridClass}">
      ${workConnected ? panel('Needs Attention','Operator Queue', attention.length ? `<div class="pm-row-list">${attention.map(workRow).join('')}</div>` : empty('Nothing urgent is sitting in the queue.'), `<button class="pm-button pm-button-ghost" data-go="work">Open Work</button>`) : ''}
      ${panel('Pitmark Pulse','Company State', `
        <div class="pm-pulse-grid">
          ${workConnected ? `<div class="pm-pulse"><header><span>Work</span>${summary.blocked ? '<b class="pm-danger-text">Blocked</b>' : '<b class="pm-good-text">Moving</b>'}</header><strong>${n(summary.open)}</strong><p>open items · ${n(summary.completed)} completed</p><div class="pm-progress"><span style="width:${Math.min(100, (Number(summary.completed||0) / Math.max(1, Number(summary.total||1))) * 100)}%"></span></div></div>` : ''}
          <div class="pm-pulse"><header><span>PRT</span><b>${n(p.testers?.redeemed)} testers</b></header><strong>${n(p.feedback?.open ?? p.feedback?.total ?? 0)}</strong><p>feedback items open · ${n(p.founders_race?.pending)} race referrals pending</p></div>
          <div class="pm-pulse"><header><span>Content</span><b>${n(c.autopilot?.scheduled)} scheduled</b></header><strong>${n(c.autopilot?.pending)}</strong><p>social approvals · ${n(c.editorial?.drafts)} editorial drafts</p></div>
          <div class="pm-pulse"><header><span>Partners</span><b>${n(relationships?.total)}</b></header><strong>${n(relationships?.waiting_follow_up)}</strong><p>records with a follow-up</p></div>
          <div class="pm-pulse"><header><span>Systems</span><b>${systems?.database?.durable_for_render ? 'Durable' : 'Check DB'}</b></header><strong>${modules.systems?.ok ? 'OK' : '!'}</strong><p>${esc(systems?.environment || 'system state unavailable')}</p></div>
          <div class="pm-pulse"><header><span>Signals</span><b>Unread</b></header><strong>${n(notifications?.unread)}</strong><p>operational notifications</p></div>
        </div>`, '')}
    </div>
    ${workConnected ? `<div class="pm-grid pm-grid-2" style="margin-top:12px">${panel('Waiting','External Dependencies', wait.length ? `<div class="pm-row-list">${wait.slice(0,6).map(workRow).join('')}</div>` : empty('Nothing is waiting right now.'), '')}${panel('Recent Progress','Momentum', (work?.recently_completed || []).length ? `<div class="pm-row-list">${work.recently_completed.slice(0,6).map(workRow).join('')}</div>` : empty('Completed work will show here.'), '')}</div>` : ''}`;
  bindWorkOpeners(root, ctx);
}

const WORK_VIEWS = ['now','today','active','waiting','monitoring','blocked','desktop','phone','completed','roadmap'];
async function renderWork(root, ctx) {
  const view = ctx.state.workView || 'now';
  const payload = await api.work(view, { maxAge: ctx.force ? 0 : 12000 });
  const items = payload?.items || []; const summary = payload?.summary || {};
  root.innerHTML = `${viewHeader('Master Checklist','Run the work, not another dashboard.','Every row comes from the live Pitmark Master Checklist.', `<span class="pm-badge ${payload.stale ? 'warn':'good'}">${payload.stale ? 'Cached':'Live source'}</span>`)}
    <div class="pm-filter-bar"><div class="pm-tabs">${WORK_VIEWS.map(v => `<button class="pm-tab ${v===view?'is-active':''}" type="button" data-work-view="${v}">${esc(v[0].toUpperCase()+v.slice(1))}${['waiting','monitoring','blocked','completed','roadmap'].includes(v) ? `<b>${n(summary[v])}</b>`:''}</button>`).join('')}</div></div>
    <div class="pm-metric-strip"><div class="pm-metric"><span>Open</span><strong>${n(summary.open)}</strong><small>all unfinished work</small></div><div class="pm-metric"><span>P1</span><strong>${n(summary.p1)}</strong><small>high-priority open work</small></div><div class="pm-metric"><span>Blocked</span><strong>${n(summary.blocked)}</strong><small>cannot move yet</small></div><div class="pm-metric"><span>Waiting</span><strong>${n(summary.waiting)}</strong><small>pending elsewhere</small></div><div class="pm-metric"><span>Done</span><strong>${n(summary.completed)}</strong><small>recorded completions</small></div></div>
    ${panel(`${view[0].toUpperCase()+view.slice(1)} Work`,'Source of Truth', items.length ? `<div class="pm-row-list">${items.map(workRow).join('')}</div>` : empty(`No ${view} items are recorded.`), `<span class="pm-badge">${n(items.length)} items</span>`)}
    ${payload.error ? `<div style="margin-top:10px">${moduleError('Live checklist refresh',payload.error)}</div>`:''}`;
  root.onclick = (event) => {
    const tab = event.target.closest('[data-work-view]'); if (tab) { ctx.state.workView = tab.dataset.workView; ctx.refresh(); return; }
    const row = event.target.closest('[data-open-work]'); if (row) openWorkItem(items.find(i => String(i.row_number) === row.dataset.openWork), ctx);
  };
}

function bindWorkOpeners(root, ctx) {
  root.onclick = (event) => {
    const go = event.target.closest('[data-go]'); if (go) { ctx.navigate(go.dataset.go); return; }
    const row = event.target.closest('[data-open-work]');
    if (row) { ctx.navigate('work', { workRow: Number(row.dataset.openWork) }); }
  };
}

function openWorkItem(item, ctx) {
  if (!item) return;
  const id = `work-notes-${item.row_number}`;
  ctx.openSheet({ kicker:`${item.area || 'Work'} · ${item.priority || 'No priority'}`, title:item.task || 'Checklist item', body:`${details([['Status',item.status],['Priority',item.priority],['Area',item.area],['Next action',item.next_action],['Last updated',item.last_updated]])}<div class="pm-detail-block"><h4>Notes</h4><textarea class="pm-textarea" id="${id}" placeholder="Add context to the Master Checklist…">${esc(item.notes || '')}</textarea></div>`, actions:[
    { label:'Save notes', tone:'ghost', run:async()=>{ await api.updateWork(item.row_number,{notes:document.getElementById(id)?.value || ''}); clearCache('/api/control/work'); ctx.toast('Master Checklist notes updated.','good'); ctx.closeSheet(); ctx.refresh(); } },
    { label:'Waiting', tone:'ghost', run:async()=>{ await api.updateWork(item.row_number,{status:'Waiting'}); clearCache('/api/control/work'); ctx.toast('Moved to Waiting.','good'); ctx.closeSheet(); ctx.refresh(); } },
    { label:'Monitoring', tone:'ghost', run:async()=>{ await api.updateWork(item.row_number,{status:'Monitoring'}); clearCache('/api/control/work'); ctx.toast('Moved to Monitoring.','good'); ctx.closeSheet();ctx.refresh(); } },
    { label:'Mark done', tone:'primary', run:async()=>{ await api.updateWork(item.row_number,{status:'Done'}); clearCache('/api/control/work'); ctx.toast('Completed and synced to Master Checklist.','good'); ctx.closeSheet(); ctx.refresh(); } },
  ]});
}

const PRT_TABS = ['applications','testers','founders','feedback'];
async function renderPRT(root, ctx) {
  const [overview, testers, race, feedback] = await Promise.allSettled([api.prtOverview(), api.prtTesters(), api.foundersRace(), api.feedback()]);
  const o = overview.status==='fulfilled'?overview.value:null; const t = testers.status==='fulfilled'?testers.value:null; const r = race.status==='fulfilled'?race.value:null; const f = feedback.status==='fulfilled'?feedback.value:null;
  const tab = ctx.state.prtTab || 'applications';
  const tabs = `<div class="pm-tabs">${[['applications','Applications',o?.applications?.new],['testers','Active Testers',t?.tester_summary?.active],['founders',"Founder’s Race",r?.summary?.pending],['feedback','Feedback',f?.summary?.open ?? f?.items?.length]].map(([key,label,count])=>`<button class="pm-tab ${tab===key?'is-active':''}" type="button" data-prt-tab="${key}">${label}<b>${n(count)}</b></button>`).join('')}</div>`;
  let body='';
  if(tab==='applications') body = t ? renderApplications(t.applications || []) : moduleError('PRT applications',testers.reason?.message,'prt');
  if(tab==='testers') body = t ? renderTesters(t.invites || []) : moduleError('PRT testers',testers.reason?.message,'prt');
  if(tab==='founders') body = r ? renderRace(r.leaderboard || []) : moduleError("Founder’s Race",race.reason?.message,'prt');
  if(tab==='feedback') body = f ? renderFeedback(f.items || []) : moduleError('PRT feedback',feedback.reason?.message,'prt');
  root.innerHTML = `${viewHeader('Product Operations','Pitmark Racing Tools','Operate the tester program, feedback loop, and Founder’s Race from one place.', `<a class="pm-button pm-button-ghost" href="/control/early-access">Applicant Center ↗</a><a class="pm-button pm-button-ghost" href="/control/founders-race">Race Admin ↗</a>`)}${tabs}${body}`;
  root.onclick = async (event) => {
    const tabButton=event.target.closest('[data-prt-tab]'); if(tabButton){ctx.state.prtTab=tabButton.dataset.prtTab;ctx.refresh();return;}
    const appAction=event.target.closest('[data-app-status]'); if(appAction){event.stopPropagation();await mutateApplication(appAction,ctx);return;}
    const fbAction=event.target.closest('[data-feedback-status]'); if(fbAction){event.stopPropagation();await mutateFeedback(fbAction,ctx);return;}
    const row=event.target.closest('[data-prt-detail]'); if(row) openPrtDetail(row.dataset.prtDetail,row.dataset.prtId,{testers:t,race:r,feedback:f},ctx);
  };
}
function renderApplications(rows){return panel('Tester Applications','PRT Intake',rows.length?`<div class="pm-table-wrap"><table class="pm-table"><thead><tr><th>Applicant</th><th>Role</th><th>Status</th><th>Submitted</th><th class="right">Action</th></tr></thead><tbody>${rows.map(row=>`<tr data-prt-detail="application" data-prt-id="${row.id}"><td><strong>${esc(titleOf(row,'Applicant'))}</strong><small>${esc(row.email || row.discord || row.iracing_name || '—')}</small></td><td>${esc(row.role || 'Driver')}</td><td>${statusBadge(row.status || 'new')}</td><td>${esc(age(row.created_at || row.submitted_at))}</td><td class="right"><div class="pm-row-actions"><button class="pm-button pm-button-ghost" data-app-status="hold" data-id="${row.id}">Hold</button><button class="pm-button pm-button-ghost" data-app-status="declined" data-id="${row.id}">Decline</button><button class="pm-button pm-button-primary" data-app-status="accepted" data-id="${row.id}">Accept</button></div></td></tr>`).join('')}</tbody></table></div>`:empty('No applications found.'))}
function renderTesters(rows){return panel('Tester Program','Early Access',rows.length?`<div class="pm-table-wrap"><table class="pm-table"><thead><tr><th>Tester</th><th>Invite</th><th>Tester state</th><th>Device</th><th>Last activity</th></tr></thead><tbody>${rows.map(row=>`<tr data-prt-detail="tester" data-prt-id="${row.id}"><td><strong>${esc(titleOf(row,'Tester'))}</strong><small>${esc(row.email || row.hub_email || '—')}</small></td><td>${statusBadge(row.status)}</td><td>${statusBadge(row.tester_status)}</td><td>${esc(row.device_id || row.bound_device_id || 'Not bound')}</td><td>${esc(age(row.last_seen_at || row.redeemed_at || row.updated_at))}</td></tr>`).join('')}</tbody></table></div>`:empty('No tester invites found.'))}
function renderRace(rows){return panel("Founder’s Race","Competition",rows.length?`<div class="pm-table-wrap"><table class="pm-table"><thead><tr><th>Pos</th><th>Participant</th><th>Qualified</th><th>Pending</th><th>Flagged</th><th>Milestone</th></tr></thead><tbody>${rows.map(row=>`<tr data-prt-detail="founders" data-prt-id="${row.tester_id || row.id || ''}"><td><strong>#${esc(row.position || '—')}</strong></td><td><strong>${esc(titleOf(row,'Participant'))}</strong><small>${esc(row.referral_code || '')}</small></td><td>${n(row.qualified)}</td><td>${n(row.pending)}</td><td>${n(row.flagged)}</td><td>${statusBadge(row.milestone_status || row.milestone || 'racing')}</td></tr>`).join('')}</tbody></table></div>`:empty('No Founder’s Race participants yet.'),`<a class="pm-button pm-button-ghost" href="/control/founders-race">Full admin ↗</a>`)}
function renderFeedback(rows){return panel('Tester Feedback','Quality Loop',rows.length?`<div class="pm-table-wrap"><table class="pm-table"><thead><tr><th>Report</th><th>Kind</th><th>Severity</th><th>Status</th><th>Age</th><th class="right">Action</th></tr></thead><tbody>${rows.map(row=>`<tr data-prt-detail="feedback" data-prt-id="${row.id}"><td><strong>${esc(row.title || row.summary || 'Feedback')}</strong><small>${esc(row.tester_name || row.reporter || row.email || '')}</small></td><td>${esc(row.kind || row.type || 'feedback')}</td><td>${statusBadge(row.severity || 'normal')}</td><td>${statusBadge(row.status || 'open')}</td><td>${esc(age(row.created_at))}</td><td class="right"><div class="pm-row-actions"><button class="pm-button pm-button-ghost" data-feedback-status="reviewing" data-id="${row.id}">Reviewing</button><button class="pm-button pm-button-primary" data-feedback-status="resolved" data-id="${row.id}">Resolve</button></div></td></tr>`).join('')}</tbody></table></div>`:empty('No feedback reports found.'))}
async function mutateApplication(button,ctx){button.disabled=true;try{await api.setApplicationStatus(button.dataset.id,button.dataset.appStatus);clearCache('/api/control/ops');ctx.toast(`Application moved to ${button.dataset.appStatus}.`,'good');ctx.refresh();}catch(e){ctx.toast(e.message,'bad');button.disabled=false;}}
async function mutateFeedback(button,ctx){button.disabled=true;try{await api.setFeedbackStatus(button.dataset.id,button.dataset.feedbackStatus);clearCache('/api/control/ops');ctx.toast(`Feedback marked ${button.dataset.feedbackStatus}.`,'good');ctx.refresh();}catch(e){ctx.toast(e.message,'bad');button.disabled=false;}}
function openPrtDetail(kind,id,data,ctx){let row;if(kind==='application')row=(data.testers?.applications||[]).find(x=>String(x.id)===String(id));if(kind==='tester')row=(data.testers?.invites||[]).find(x=>String(x.id)===String(id));if(kind==='founders')row=(data.race?.leaderboard||[]).find(x=>String(x.tester_id||x.id)===String(id));if(kind==='feedback')row=(data.feedback?.items||[]).find(x=>String(x.id)===String(id));if(!row)return;ctx.openSheet({kicker:kind,title:titleOf(row,kind),body:`${details(Object.entries(row).filter(([k])=>!['notes','body','description'].includes(k)).slice(0,14))}${row.notes||row.body||row.description?`<div class="pm-detail-block"><h4>Details</h4><p>${esc(row.notes||row.body||row.description)}</p></div>`:''}`,actions:[{label:'Close',tone:'ghost',run:ctx.closeSheet}]});}

const CONTENT_TABS = ['generated','approval','scheduled','published','archived','editorial'];
async function renderContent(root,ctx){const tab=ctx.state.contentTab||'generated';let rows=[];let editorial=[];try{if(tab==='editorial'){editorial=await api.blogDrafts();}else if(tab==='generated'){rows=await api.posts();}else if(tab==='approval'){rows=await api.posts('pending');}else if(tab==='archived'){const [a,b]=await Promise.all([api.posts('archived'),api.posts('rejected')]);rows=[...a,...b];}else{rows=await api.posts(tab);}}catch(e){root.innerHTML=moduleError('Content',e.message,'content');return;}const tabs=`<div class="pm-tabs">${CONTENT_TABS.map(key=>`<button class="pm-tab ${tab===key?'is-active':''}" type="button" data-content-tab="${key}">${key==='approval'?'Needs Approval':key[0].toUpperCase()+key.slice(1)}</button>`).join('')}</div>`;root.innerHTML=`${viewHeader('Social Manager','Content operations without image generation.','Review generated copy, approve or schedule posts, and keep editorial separate.',`<button class="pm-button pm-button-primary" type="button" data-compose>New post</button>`)}${tabs}${tab==='editorial'?renderEditorial(editorial):renderPosts(rows,tab)}`;root.onclick=(event)=>{const t=event.target.closest('[data-content-tab]');if(t){ctx.state.contentTab=t.dataset.contentTab;ctx.refresh();return;}if(event.target.closest('[data-compose]')){openComposer(ctx);return;}const p=event.target.closest('[data-post-id]');if(p)openPost(rows.find(x=>String(x.id)===p.dataset.postId),ctx);const b=event.target.closest('[data-blog-id]');if(b)openBlog(editorial.find(x=>String(x.id)===b.dataset.blogId),ctx);};}
function renderPosts(rows,tab){return panel(tab==='approval'?'Needs Approval':'Autopilot Posts','Generated Social',rows.length?`<div class="pm-row-list">${rows.map(row=>`<button class="pm-row" type="button" data-post-id="${row.id}"><div class="pm-row-main"><div class="pm-row-meta"><span class="pm-badge orange">${esc(row.platform||'social')}</span>${statusBadge(row.status)}${row.media_url?'<span class="pm-badge">Media</span>':''}</div><strong>${esc(row.title||compact(row.body,80)||'Generated post')}</strong><p>${esc(compact(row.body,170))}</p></div><div class="pm-row-side"><span class="pm-muted">${esc(row.scheduled_for?dateText(row.scheduled_for):age(row.created_at))}</span><span>›</span></div></button>`).join('')}</div>`:empty('No posts in this view.'))}
function renderEditorial(rows){return panel('Editorial','Blog & News',rows.length?`<div class="pm-row-list">${rows.map(row=>`<button class="pm-row" type="button" data-blog-id="${row.id}"><div class="pm-row-main"><div class="pm-row-meta"><span class="pm-badge">${esc(row.content_type||'article')}</span>${statusBadge(row.status)}</div><strong>${esc(row.title)}</strong><p>${esc(compact(String(row.body_html||'').replace(/<[^>]+>/g,' '),150))}</p></div><div class="pm-row-side"><span class="pm-muted">${esc(age(row.updated_at||row.created_at))}</span><span>›</span></div></button>`).join('')}</div>`:empty('No editorial drafts found.'))}
function openPost(row,ctx){if(!row)return;const titleId=`post-title-${row.id}`,bodyId=`post-body-${row.id}`;ctx.openSheet({kicker:`${row.platform||'Social'} · ${row.status||'unknown'}`,title:row.title||'Generated post',body:`<div class="pm-form"><div class="pm-field"><label>Title</label><input class="pm-input" id="${titleId}" value="${esc(row.title||'')}"></div><div class="pm-field"><label>Post copy</label><textarea class="pm-textarea" id="${bodyId}" style="min-height:220px">${esc(row.body||'')}</textarea></div>${details([['Source',row.source],['Created',dateText(row.created_at)],['Scheduled',dateText(row.scheduled_for)],['Media',row.media_url||'None']])}</div>`,actions:[{label:'Copy',tone:'ghost',run:async()=>{await navigator.clipboard.writeText(document.getElementById(bodyId)?.value||'');ctx.toast('Post copied.','good');}},{label:'Archive',tone:'ghost',run:()=>postDecision(row.id,'archive',ctx)},{label:'Reject',tone:'danger',run:()=>postDecision(row.id,'reject',ctx)},{label:'Save',tone:'ghost',run:async()=>{await api.updatePost(row.id,{title:document.getElementById(titleId)?.value||'',body:document.getElementById(bodyId)?.value||''});clearCache('/api/control/autopilot/posts');ctx.toast('Post updated.','good');ctx.closeSheet();ctx.refresh();}},{label:'Approve',tone:'primary',run:()=>postDecision(row.id,'approve',ctx)}]});}
async function postDecision(id,action,ctx){try{await api.decidePost(id,action);clearCache('/api/control/autopilot/posts');ctx.toast(`Post ${action}d.`,'good');ctx.closeSheet();ctx.refresh();}catch(e){ctx.toast(e.message,'bad');}}
function openComposer(ctx){const topic='composer-topic',platform='composer-platform',body='composer-body';ctx.openSheet({kicker:'Autopilot Composer',title:'Create social copy',body:`<div class="pm-form"><div class="pm-form-grid"><div class="pm-field"><label>Platform</label><select class="pm-select" id="${platform}"><option>facebook</option><option>instagram</option><option>x</option><option>tiktok</option><option>discord</option></select></div><div class="pm-field"><label>Goal</label><select class="pm-select" id="composer-goal"><option value="community">Community</option><option value="authority">Authority</option><option value="education">Education</option><option value="product">Product</option></select></div></div><div class="pm-field"><label>Topic / prompt</label><textarea class="pm-textarea" id="${topic}" placeholder="What should Pitmark talk about?"></textarea></div><div class="pm-field"><label>Generated copy</label><textarea class="pm-textarea" id="${body}" placeholder="Generate first, then edit here."></textarea></div></div>`,actions:[{label:'Generate',tone:'ghost',run:async()=>{try{const result=await api.compose({platform:document.getElementById(platform).value,goal:document.getElementById('composer-goal').value,topic:document.getElementById(topic).value,prompt:document.getElementById(topic).value,tone:'pitmark',use_context:true});document.getElementById(body).value=result.body||'';ctx.toast('Copy generated.','good');}catch(e){ctx.toast(e.message,'bad');}}},{label:'Save to queue',tone:'primary',run:async()=>{try{await api.savePost({platform:document.getElementById(platform).value,title:compact(document.getElementById(topic).value,160),body:document.getElementById(body).value,content_type:'community',source:'control_center',risk:'low'});clearCache('/api/control/autopilot/posts');ctx.toast('Post saved to approval queue.','good');ctx.closeSheet();ctx.refresh();}catch(e){ctx.toast(e.message,'bad');}}}]});}
function openBlog(row,ctx){if(!row)return;ctx.openSheet({kicker:`Editorial · ${row.status||'draft'}`,title:row.title,body:`${details([['Type',row.content_type],['Status',row.status],['Updated',dateText(row.updated_at)],['Scheduled',dateText(row.scheduled_for)]])}<div class="pm-detail-block"><h4>Draft</h4><p>${esc(String(row.body_html||'').replace(/<[^>]+>/g,' '))}</p></div>`,actions:[{label:'Archive',tone:'ghost',run:async()=>{await api.decideBlog(row.id,'archive');clearCache('/api/control/blog/drafts');ctx.toast('Draft archived.','good');ctx.closeSheet();ctx.refresh();}},{label:'Approve',tone:'primary',run:async()=>{await api.decideBlog(row.id,'approve');clearCache('/api/control/blog/drafts');ctx.toast('Draft approved.','good');ctx.closeSheet();ctx.refresh();}}]});}

async function renderPartnerships(root,ctx){let rows;try{rows=await api.outreach();}catch(e){root.innerHTML=moduleError('Relationships',e.message,'partnerships');return;}const stages=rows.reduce((a,r)=>(a[low(r.stage)||'unknown']=(a[low(r.stage)||'unknown']||0)+1,a),{});root.innerHTML=`${viewHeader('Relationship Operations','Partnerships','A lightweight operating CRM for tracks, leagues, partners, broadcasters, and opportunities.')}<div class="pm-metric-strip"><div class="pm-metric"><span>Total relationships</span><strong>${n(rows.length)}</strong><small>tracked records</small></div><div class="pm-metric"><span>Prospects</span><strong>${n(stages.prospect||stages.new)}</strong><small>early-stage relationships</small></div><div class="pm-metric"><span>Active</span><strong>${n(stages.active||stages.partner)}</strong><small>active relationships</small></div><div class="pm-metric"><span>Waiting</span><strong>${n(stages.waiting)}</strong><small>pending next move</small></div><div class="pm-metric"><span>Follow-ups</span><strong>${n(rows.filter(r=>r.next_follow_up).length)}</strong><small>next action recorded</small></div></div>${panel('Relationship Pipeline','Real-world + sim network',rows.length?`<div class="pm-table-wrap"><table class="pm-table"><thead><tr><th>Organization / person</th><th>Type</th><th>Stage</th><th>Support</th><th>Next follow-up</th></tr></thead><tbody>${rows.map(r=>`<tr data-outreach-id="${r.id}"><td><strong>${esc(r.organization||r.name)}</strong><small>${esc(r.organization?r.name:'')}</small></td><td>${esc(r.contact_type||'Other')}</td><td>${statusBadge(r.stage)}</td><td>${esc(r.supporter_status||'—')}</td><td>${esc(r.next_follow_up||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('No relationship records found.'))}`;root.onclick=(e)=>{const tr=e.target.closest('[data-outreach-id]');if(tr)openRelationship(rows.find(r=>String(r.id)===tr.dataset.outreachId),ctx);};}
function openRelationship(row,ctx){if(!row)return;const stage=`rel-stage-${row.id}`,follow=`rel-follow-${row.id}`,notes=`rel-notes-${row.id}`;ctx.openSheet({kicker:row.contact_type||'Relationship',title:row.organization||row.name,body:`${details([['Contact',row.name],['Stage',row.stage],['Supporter state',row.supporter_status],['Contact channel',row.email||'Not recorded']])}<div class="pm-form"><div class="pm-form-grid"><div class="pm-field"><label>Stage</label><input class="pm-input" id="${stage}" value="${esc(row.stage||'')}"></div><div class="pm-field"><label>Next follow-up</label><input class="pm-input" id="${follow}" value="${esc(row.next_follow_up||'')}"></div></div><div class="pm-field"><label>Notes</label><textarea class="pm-textarea" id="${notes}">${esc(row.notes||'')}</textarea></div></div>`,actions:[{label:'Save relationship',tone:'primary',run:async()=>{await api.updateOutreach(row.id,{stage:document.getElementById(stage).value,next_follow_up:document.getElementById(follow).value,notes:document.getElementById(notes).value});clearCache('/api/control/outreach');ctx.toast('Relationship updated.','good');ctx.closeSheet();ctx.refresh();}}]});}

async function renderStore(root,ctx){const results=await Promise.allSettled(['active','waiting','monitoring','roadmap'].map(v=>api.work(v)));const all=results.filter(x=>x.status==='fulfilled').flatMap(x=>x.value.items||[]);const unique=[...new Map(all.map(i=>[i.row_number,i])).values()];const rows=unique.filter(i=>/(store|brand|web|commerce|shopify|merchant|tiktok shop|product)/i.test(`${i.area} ${i.task}`));root.innerHTML=`${viewHeader('Commerce Operations','Store & Brand','Real store, web, product, launch, and brand work from the Master Checklist.')} ${panel('Store & Brand Work','Master Checklist',rows.length?`<div class="pm-row-list">${rows.map(workRow).join('')}</div>`:empty('No open Store & Brand checklist work matches the current source.'))}`;root.onclick=(e)=>{const row=e.target.closest('[data-open-work]');if(row)openWorkItem(rows.find(i=>String(i.row_number)===row.dataset.openWork),ctx);};}

async function renderPeople(root,ctx){const [testersResult,outreachResult,raceResult]=await Promise.allSettled([api.prtTesters(),api.outreach(),api.foundersRace()]);const testers=testersResult.status==='fulfilled'?(testersResult.value.invites||[]):[];const outreach=outreachResult.status==='fulfilled'?outreachResult.value:[];const race=raceResult.status==='fulfilled'?(raceResult.value.leaderboard||[]):[];root.innerHTML=`${viewHeader('Pitmark Network','People','Testers and relationship contacts without duplicating their source systems.')}<div class="pm-grid pm-grid-2">${panel('PRT Testers','Product Community',testers.length?`<div class="pm-row-list">${testers.slice(0,30).map(r=>`<div class="pm-row"><div class="pm-row-main"><strong>${esc(titleOf(r,'Tester'))}</strong><p>${esc(r.email||r.hub_email||'')} · ${esc(r.tester_status||r.status||'unknown')}</p></div><div class="pm-row-side">${statusBadge(r.status)}</div></div>`).join('')}</div>`:empty('No testers loaded.'))}${panel('Relationships','Business Network',outreach.length?`<div class="pm-row-list">${outreach.slice(0,30).map(r=>`<div class="pm-row"><div class="pm-row-main"><strong>${esc(r.organization||r.name)}</strong><p>${esc(r.contact_type||'Other')} · ${esc(r.stage||'unknown')}</p></div><div class="pm-row-side">${statusBadge(r.stage)}</div></div>`).join('')}</div>`:empty('No relationships loaded.'))}</div>${panel("Founder’s Race",'Community Competition',race.length?`<div class="pm-row-list">${race.slice(0,12).map(r=>`<div class="pm-row"><div class="pm-row-main"><strong>#${esc(r.position||'—')} ${esc(titleOf(r,'Participant'))}</strong><p>${n(r.qualified)} qualified · ${n(r.pending)} pending referrals</p></div><div class="pm-row-side"><span class="pm-badge orange">${esc(r.referral_code||'Racing')}</span></div></div>`).join('')}</div>`:empty('No race participants loaded.'))}`;}

async function renderSystems(root,ctx){const [statusResult,briefResult,notifyResult,hqResult]=await Promise.allSettled([api.status(),api.brief(),api.notifications(),api.hq()]);const status=statusResult.status==='fulfilled'?statusResult.value:null;const brief=briefResult.status==='fulfilled'?briefResult.value:null;const notifications=notifyResult.status==='fulfilled'?notifyResult.value:[];const systemModule=hqResult.status==='fulfilled'?unwrap(hqResult.value?.modules?.systems):null;root.innerHTML=`${viewHeader('Platform Operations','Systems','Human-readable Pitmark Cloud health and current operating signals.')}<div class="pm-grid pm-grid-3">${panel('Pitmark Cloud','Runtime',status?`${details([['Version',systemModule?.app_version||'—'],['Environment',systemModule?.environment||'—'],['Autopilot service',status.autopilot?'Available':'Unavailable'],['Outreach records',status.outreach_contacts],['Blog drafts',status.blog_drafts]])}`:moduleError('Status',statusResult.reason?.message))}${panel('Command Brief','Operations',brief?`<div class="pm-detail-block"><p>${esc(compact(brief.summary||brief.brief||brief.message||JSON.stringify(brief),900))}</p></div>`:moduleError('Command brief',briefResult.reason?.message))}${panel('Signals','Notifications',Array.isArray(notifications)?(notifications.length?`<div class="pm-row-list">${notifications.slice(0,8).map(r=>`<div class="pm-row"><div class="pm-row-main"><strong>${esc(r.title||r.module||'Signal')}</strong><p>${esc(compact(r.detail||r.reason||'',120))}</p></div><div class="pm-row-side">${statusBadge(r.priority||r.status||'info')}</div></div>`).join('')}</div>`:empty('No current signals.')):empty('Signals unavailable.'))}</div>`;}

async function renderInsights(root,ctx){const payload=await api.hq();const m=payload.modules||{};const work=unwrap(m.work)||{};const prt=unwrap(m.prt)||{};const content=unwrap(m.content)||{};const rel=unwrap(m.relationships)||{};const s=work.summary||{};root.innerHTML=`${viewHeader('Operating Intelligence','Insights','Current operational momentum from real Pitmark sources—not vanity metrics.')}<div class="pm-metric-strip"><div class="pm-metric"><span>Open work</span><strong>${n(s.open)}</strong><small>${n(s.p1)} P1 · ${n(s.blocked)} blocked</small></div><div class="pm-metric"><span>Completed</span><strong>${n(s.completed)}</strong><small>Master Checklist history</small></div><div class="pm-metric"><span>PRT testers</span><strong>${n(prt.testers?.redeemed)}</strong><small>${n(prt.applications?.new)} new applications</small></div><div class="pm-metric"><span>Content queue</span><strong>${n(content.autopilot?.pending)}</strong><small>${n(content.autopilot?.scheduled)} scheduled</small></div><div class="pm-metric"><span>Relationships</span><strong>${n(rel.total)}</strong><small>${n(rel.waiting_follow_up)} follow-ups</small></div></div><div class="pm-grid pm-grid-2">${panel('Work Momentum','Source of Truth',`<div class="pm-pulse-grid"><div class="pm-pulse"><header><span>Active</span></header><strong>${n(s.active)}</strong><p>currently moving</p></div><div class="pm-pulse"><header><span>Monitoring</span></header><strong>${n(s.monitoring)}</strong><p>being watched</p></div><div class="pm-pulse"><header><span>Waiting</span></header><strong>${n(s.waiting)}</strong><p>external dependencies</p></div><div class="pm-pulse"><header><span>Roadmap</span></header><strong>${n(s.roadmap)}</strong><p>future work</p></div></div>`)}${panel('Growth Activity','Operational Snapshot',`<div class="pm-detail-list"><div class="pm-detail-pair"><span>Founder’s Race pending</span><strong>${n(prt.founders_race?.pending)}</strong></div><div class="pm-detail-pair"><span>PRT feedback</span><strong>${n(prt.feedback?.open??prt.feedback?.total)}</strong></div><div class="pm-detail-pair"><span>Editorial drafts</span><strong>${n(content.editorial?.drafts)}</strong></div><div class="pm-detail-pair"><span>Published social</span><strong>${n(content.autopilot?.published)}</strong></div></div>`)}</div>`;}

export async function renderDomain(domain, root, ctx) {
  root.onclick = null;
  root.innerHTML = `<div class="pm-view-skeleton"><div class="pm-skeleton pm-skeleton-line wide"></div><div class="pm-skeleton-grid"><div class="pm-skeleton block"></div><div class="pm-skeleton block"></div><div class="pm-skeleton block"></div></div></div>`;
  try {
    if (domain === 'hq') return await renderHQ(root,ctx);
    if (domain === 'work') return await renderWork(root,ctx);
    if (domain === 'prt') return await renderPRT(root,ctx);
    if (domain === 'partnerships') return await renderPartnerships(root,ctx);
    if (domain === 'content') return await renderContent(root,ctx);
    if (domain === 'store') return await renderStore(root,ctx);
    if (domain === 'people') return await renderPeople(root,ctx);
    if (domain === 'systems') return await renderSystems(root,ctx);
    if (domain === 'insights') return await renderInsights(root,ctx);
    throw new Error(`Unknown Pitmark operating area: ${domain}`);
  } catch (error) {
    if (error?.name === 'AbortError') return;
    root.innerHTML = `${viewHeader('Control Center','This workspace hit a problem.','Other Pitmark areas are still available.')} ${moduleError(DOMAIN_META[domain]?.title || domain,error?.message || String(error),domain)}`;
    root.onclick = (event) => { if (event.target.closest('[data-retry]')) ctx.refresh(true); };
  }
}
