
let pitmarkToastTimer;
function showToast(title,message,type='success'){const t=$('pitmarkToast');if(!t)return;t.className='pitmark-toast '+(['error','warning','info'].includes(type)?type:'');t.innerHTML=`<strong>${esc(title)}</strong><span>${esc(message)}</span>`;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(pitmarkToastTimer);pitmarkToastTimer=setTimeout(()=>t.classList.remove('show'),4200)}
let generated='';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function apiCall(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let data;try{data=JSON.parse(t)}catch{data=t}if(r.status===401){location.href='/control';throw new Error('Session expired.')}if(!r.ok)throw new Error((data&&data.detail)||t||('HTTP '+r.status));return data}
function setView(name){document.querySelectorAll('[data-view-section]').forEach(x=>x.classList.toggle('active',x.dataset.viewSection===name));function rookieCard(r){
 const stages=['prospect','interested','intake_sent','submitted','verification','ready_for_review','selected','story_building','racer_review','scheduled','published','alumni'];
 const job=r.research_job;
 const jobStatus=job?String(job.status||'queued'):'none';
 const jobLabel=job?`Research ${esc(jobStatus)} · Job #${job.id}`:'';
 const view=job?`<button class="btn ghost mini" data-ry-view data-job="${job.id}">${jobStatus==='complete'?'View Research':'Check Research'}</button>`:'';
 return `<article class="record-card rookie-card" data-id="${r.id}"><div class="record-row"><strong>${esc(r.name)}</strong><span class="status-pill">${esc(r.stage)}</span></div><div class="meta"><span>Intake: ${esc(r.intake_status)}</span><span>Verification: ${esc(r.verification_status)}</span><span>Media: ${esc(r.media_permission)}</span><span>Guardian: ${esc(r.guardian_status)}</span>${job?`<span class="research-chip research-${esc(jobStatus)}">${jobLabel}</span>`:''}</div><div class="outreach-fields"><select class="select" data-ry-stage>${stages.map(x=>`<option value="${x}" ${x===r.stage?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select><select class="select" data-ry-intake><option value="not_sent" ${r.intake_status==='not_sent'?'selected':''}>Intake not sent</option><option value="sent" ${r.intake_status==='sent'?'selected':''}>Intake sent</option><option value="received" ${r.intake_status==='received'?'selected':''}>Intake received</option></select><select class="select" data-ry-media><option value="pending" ${r.media_permission==='pending'?'selected':''}>Media pending</option><option value="approved" ${r.media_permission==='approved'?'selected':''}>Media approved</option></select><button class="btn secondary mini" data-ry-save>Save</button><button class="btn mini" data-ry-research data-entity="${r.entity_id}">Research & Prepare</button>${view}</div><div class="research-detail" data-research-detail></div></article>`
}
async function loadRookies(){try{const x=await apiCall('/api/control/campaigns/rookie-year');const a=x.participants||[];$('rookieOutput').innerHTML=a.length?a.map(rookieCard).join(''):'<div class="empty-state">No Rookie Year participants yet.</div>';$('ryInterested').textContent=a.filter(x=>x.stage==='interested').length;$('rySent').textContent=a.filter(x=>['sent','received'].includes(x.intake_status)).length;$('ryReady').textContent=a.filter(x=>['ready_for_review','selected','story_building'].includes(x.stage)).length;$('ryPublished').textContent=a.filter(x=>['published','alumni'].includes(x.stage)).length}catch(e){$('rookieOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function addRookie(){try{await apiCall('/api/control/campaigns/rookie-year/participants',{method:'POST',body:JSON.stringify({name:$('ryName').value,community_lane:$('ryLane').value,stage:$('ryStage').value,intake_status:$('ryStage').value==='intake_sent'?'sent':'not_sent'})});$('ryName').value='';loadRookies()}catch(e){showToast('Action Failed',e.message,'error')}}
async function rookieAction(e){const save=e.target.closest('[data-ry-save]'),research=e.target.closest('[data-ry-research]');if(save){const c=save.closest('.rookie-card');await apiCall('/api/control/campaigns/rookie-year/participants/'+c.dataset.id,{method:'POST',body:JSON.stringify({stage:c.querySelector('[data-ry-stage]').value,intake_status:c.querySelector('[data-ry-intake]').value,media_permission:c.querySelector('[data-ry-media]').value})});loadRookies()}if(research){try{research.disabled=true;research.textContent='Queuing…';const x=await apiCall('/api/control/community/research/prepare',{method:'POST',body:JSON.stringify({entity_id:Number(research.dataset.entity),research_type:'rookie_deep_dive'})});showToast('Research Job Queued ✓',x.subject+' · Job #'+x.job_id+' · No outreach will be sent without approval.');await loadRookies()}catch(err){showToast('Research Job Failed',err.message,'error')}finally{research.disabled=false;research.textContent='Research & Prepare'}}}
document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'instant'});if(name==='dashboard')loadStatus();if(name==='autopilot'){loadQueue();loadIntelligence();loadPlanner();loadAutonomy()}if(name==='shield')loadShield();if(name==='campaigns')loadRookies();if(name==='outreach')loadOutreach();if(name==='blog')loadBlog();if(name==='settings'){loadConnections();loadAutonomy()}}
async function loadSession(){const me=await apiCall('/api/control/auth/me');$('sessionUser').textContent=(me.username||'admin').toUpperCase()}
async function loadStatus(){try{const x=await apiCall('/api/control/status');const stats=[['statPosts',x.social_pending],['statShield',x.shield_review],['statOutreach',x.outreach_contacts],['statBlog',x.blog_drafts]];stats.forEach(([id,value])=>{const el=$(id);el.textContent=value;el.closest('.stat-card')?.classList.toggle('attention',Number(value)>0)});await loadCommandBrief()}catch(e){console.error(e)}}
let selectedInstagramAsset=null;
let uploadedInstagramUrl=null;
function activePlatform(){return String($('platform')?.value||'facebook').toLowerCase()}
function assetMode(){return document.querySelector('input[name="igAssetMode"]:checked')?.value||'auto'}
function renderAssetPreview(box,url,label='Pitmark asset',assetId=null){if(!box)return;if(!url){box.innerHTML='<span>No image selected yet.</span>';return}const previewUrl=assetId?`/api/control/social/assets/${encodeURIComponent(assetId)}/preview`:url;box.innerHTML=`<div class="asset-image-stage"><img src="${esc(previewUrl)}" alt="${esc(label)}"><div class="asset-preview-error hidden">Preview could not load. Try another image.</div></div><div class="asset-preview-caption"><strong>${esc(label)}</strong>${assetId?'<span>Pitmark Asset Library</span>':'<span>Local upload preview</span>'}</div>`;const img=box.querySelector('img');img?.addEventListener('error',()=>{img.classList.add('hidden');box.querySelector('.asset-preview-error')?.classList.remove('hidden')})}
function syncComposerPlatform(){const ig=activePlatform()==='instagram';$('instagramAssetPanel')?.classList.toggle('hidden',!ig);if(ig&&generated&&!selectedInstagramAsset&&assetMode()==='auto')suggestInstagramAsset()}
function syncAssetMode(){const upload=assetMode()==='upload';$('igAutoAsset')?.classList.toggle('hidden',upload);$('igUploadAsset')?.classList.toggle('hidden',!upload)}
async function suggestInstagramAsset(){if(activePlatform()!=='instagram')return;const b=$('suggestAssetBtn');if(b){b.disabled=true;b.textContent='Choosing…'}try{const body=$('draftEditor')?.value||generated||'';const x=await apiCall('/api/control/social/assets/suggest',{method:'POST',body:JSON.stringify({body,content_type:$('goal').value})});selectedInstagramAsset=x.asset||null;renderAssetPreview($('igAssetPreview'),selectedInstagramAsset?.url,selectedInstagramAsset?.title||'Pitmark asset',selectedInstagramAsset?.id||null);if(!selectedInstagramAsset)$('composerMessage').textContent='No asset available yet — sync Shopify images or upload one.'}catch(e){$('composerMessage').textContent=e.message}finally{if(b){b.disabled=false;b.textContent='Choose / Refresh Image'}}}
async function uploadInstagramAsset(){const file=$('igUploadInput')?.files?.[0];if(!file)throw new Error('Choose an image first.');if(file.size>6*1024*1024)throw new Error('Image must be 6 MB or smaller.');const r=await fetch('/api/control/social/assets/upload',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type,'X-Pitmark-Filename':file.name,'X-Pitmark-Add-To-Library':$('igAddLibrary')?.checked?'true':'false'},body:file});const t=await r.text();let x;try{x=JSON.parse(t)}catch{x={detail:t}}if(r.status===401){location.href='/control';throw new Error('Session expired.')}if(!r.ok)throw new Error(x.detail||'Upload failed.');uploadedInstagramUrl=x.url;return x.url}
async function composePost(){try{const p=activePlatform(),g=$('goal').value,t=$('topic').value.trim();const x=await apiCall('/api/control/autopilot/composer/generate',{method:'POST',body:JSON.stringify({platform:p,goal:g,prompt:t||'Generate a useful Pitmark post',topic:t||null})});generated=x.body;$('draftEditor').value=x.body;$('composerMessage').textContent='Draft ready — edit anything you want before saving.';if(p==='instagram'&&assetMode()==='auto')await suggestInstagramAsset()}catch(e){$('composerMessage').textContent='ERROR: '+e.message}}
async function savePost(){const body=$('draftEditor').value.trim();if(!body){$('composerMessage').textContent='Draft is empty.';return}$('savePostBtn').disabled=true;try{const platform=activePlatform();let media_url=null;if(platform==='instagram'){if(assetMode()==='upload')media_url=await uploadInstagramAsset();else{if(!selectedInstagramAsset)await suggestInstagramAsset();media_url=selectedInstagramAsset?.url||null}}const x=await apiCall('/api/control/autopilot/posts',{method:'POST',body:JSON.stringify({platform,body,content_type:$('goal').value,source:'manual',media_url})});$('composerMessage').textContent=`Saved as #${x.id} (${x.status}).`;generated=body;await loadQueue();await loadStatus()}catch(e){$('composerMessage').textContent='SAVE ERROR: '+e.message}finally{$('savePostBtn').disabled=false}}
let socialPublishStatus={facebook:false,instagram:false,x:false};
async function loadSocialPublishStatus(){try{const x=await apiCall('/api/control/social/status');socialPublishStatus.facebook=Boolean(x?.facebook?.configured);socialPublishStatus.instagram=Boolean(x?.instagram?.configured);socialPublishStatus.x=Boolean(x?.x?.configured);return x}catch(e){socialPublishStatus={facebook:false,instagram:false,x:false};console.warn('Social publishing status unavailable:',e);return {}}}
function ageLabel(minutes){const m=Math.max(0,Number(minutes)||0);if(m<1)return 'just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ${m%60?`${m%60}m `:''}ago`;return `${Math.floor(h/24)}d ago`}
function queueCard(p){const when=p.scheduled_for?`<span>Scheduled: ${esc(p.scheduled_for)}</span>`:'';const canApprove=p.status==='pending'&&!p.stale_for_social;const canSchedule=['pending','approved'].includes(p.status)&&!p.stale_for_social;const platform=String(p.platform||'').toLowerCase();const connected=Boolean(socialPublishStatus[platform]);const canPublish=['facebook','instagram','x'].includes(platform)&&connected&&['approved','scheduled'].includes(p.status)&&!p.stale_for_social;const freshness=p.stale_for_social?'expired':(p.timeline_bucket==='now'?'now':'recent');const sourceAge=p.source_age_minutes!=null?`<span class="freshness-chip ${freshness}">${p.stale_for_social?'EXPIRED · ':''}${esc(ageLabel(p.source_age_minutes))}</span>`:'';const sourceTime=p.source_published_at?`<span>Source published ${esc(new Date(p.source_published_at).toLocaleString())}</span>`:'';const media=platform==='instagram'?(p.media_url?`<div class="queue-media-preview"><img src="${esc(p.media_url)}" alt="Instagram image"></div>`:'<span>Image: auto-select on publish</span>'):'';const expired=p.stale_for_social?'<div class="note">Expired from the real-time social lane. Keep the topic for long-form/blog use instead of publishing it late.</div>':'';return `<article class="queue-card" data-id="${p.id}"><div class="queue-card-top"><div><span class="status-pill status-${esc(p.status)}">${esc(p.status)}</span><strong>#${p.id} · ${esc(p.platform)}</strong><span>${esc(p.content_type)} · ${esc(p.source)}</span>${sourceAge}${sourceTime}${when}</div><span>${esc((p.timeline_at||p.created_at||'').replace('T',' ').slice(0,16))}</span></div><div class="queue-body">${esc(p.body)}</div>${media}${expired}<div class="queue-actions">${canApprove?'<button class="btn mini" data-action="approve">Approve</button>':''}${!p.stale_for_social?'<button class="btn secondary mini" data-action="reject">Reject</button>':''}${canSchedule?'<input class="input schedule-input" type="datetime-local"><button class="btn secondary mini" data-action="schedule">Schedule</button>':''}<button class="btn ghost mini" data-action="archive">Archive</button>${platform==='instagram'&&!p.stale_for_social?'<button class="btn ghost mini" data-action="asset">Refresh Image</button>':''}<button class="btn ghost mini" data-action="publish" ${canPublish?'':'disabled'}>Publish</button></div></article>`}
function renderTimeline(posts){if(!posts.length)return '<div class="empty-state">No posts in this timeline yet.</div>';const order=['now','recent','scheduled','published','expired','older'];const labels={now:'NOW',recent:'RECENT',scheduled:'SCHEDULED',published:'PUBLISHED',expired:'EXPIRED',older:'OLDER / MANUAL'};return order.map(bucket=>{const rows=posts.filter(p=>(p.timeline_bucket||'older')===bucket);if(!rows.length)return '';return `<section class="timeline-group"><div class="timeline-group-head"><strong>${labels[bucket]}</strong><span>${rows.length} ${rows.length===1?'item':'items'}</span></div><div class="timeline-line">${rows.map(queueCard).join('')}</div></section>`}).join('')}
async function loadQueue(){try{await loadSocialPublishStatus();const filter=$('queueFilter').value;const posts=await apiCall('/api/control/autopilot/posts'+(filter?'?status='+encodeURIComponent(filter):''));$('queueList').innerHTML=renderTimeline(posts)}catch(e){$('queueList').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function queueAction(card,action){const id=card.dataset.id;if(action==='asset'){try{const x=await apiCall(`/api/control/social/posts/${id}/assign-asset`,{method:'POST'});showToast('Image Selected ✓',x?.asset?.title||'Pitmark image assigned.');await loadQueue()}catch(e){showToast('Image Selection Failed',e.message,'error')}return}if(action==='publish'){try{const x=await apiCall(`/api/control/social/posts/${id}/publish`,{method:'POST'});const p=String(x?.post?.platform||'social');showToast('Published ✓',p.charAt(0).toUpperCase()+p.slice(1)+' post is live.');await loadQueue();await loadStatus()}catch(e){showToast('Publish Failed',e.message,'error')}return}const payload={action};if(action==='schedule'){const input=card.querySelector('.schedule-input');if(!input.value){input.focus();return}payload.scheduled_for=input.value}try{await apiCall(`/api/control/autopilot/posts/${id}/decision`,{method:'POST',body:JSON.stringify(payload)});await loadQueue();await loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
async function loadIntelligence(){try{const st=await apiCall('/api/control/autopilot/intelligence/status');$('intelStatus').textContent=st.enabled?('AUTO · EVERY '+(st.interval_minutes||60)+' MIN'):'DISABLED';if(st.last_run){const r=st.last_run;$('intelSummary').textContent=`Last scan ${r.status}: ${r.found} new signals found · ${r.queued} candidates queued${r.queued===0?' · nothing strong enough to add to the approval queue':''}.`}else{$('intelSummary').textContent='No intelligence scan has run yet.'}const ops=await apiCall('/api/control/autopilot/opportunities');const eng=await apiCall('/api/control/autopilot/opportunity-engine');const byId=Object.fromEntries((eng.opportunities||[]).map(x=>[x.opportunity_id,x]));$('opportunityList').innerHTML=ops.length?ops.slice(0,8).map(o=>{const e=byId[o.id];return `<article class="record-card"><strong>${esc(o.headline)}</strong><span>${e?'Opportunity '+e.score+'/100 · '+esc(e.recommended_action.replaceAll('_',' ')):esc(o.relevance)} · ${esc(o.reason||'')}</span>${e&&e.strengths.length?`<small>WHY PITMARK CARES · ${esc(e.strengths[0])}</small>`:''}${e&&e.weaknesses.length?`<small>WATCH · ${esc(e.weaknesses[0])}</small>`:''}${o.freshness?`<small>FRESHNESS · ${esc(o.freshness.status.toUpperCase())}${o.freshness.age_hours!=null?' · '+o.freshness.age_hours+'H OLD':''}</small>`:''}<a href="${esc(o.source_url)}" target="_blank" rel="noopener">Source ↗</a></article>`}).join(''):'<div class="empty-state">No opportunities yet. Run Intelligence Now.</div>'}catch(e){$('opportunityList').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function runIntelligence(){const b=$('runIntelBtn');b.disabled=true;b.textContent='Scanning…';try{const x=await apiCall('/api/control/autopilot/intelligence/run',{method:'POST'});$('intelSummary').textContent=`Scan complete — ${x.found} new signals found · ${x.queued} candidates queued${x.queued===0?' · nothing strong enough to queue':''}.`;await loadIntelligence();await loadQueue();await loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}finally{b.disabled=false;b.textContent='Run Intelligence Now'}}

function briefItem(x){const go=x.action_view?`<button class="btn ghost mini" data-brief-go="${esc(x.action_view)}">Open ${esc(x.module)}</button>`:'';return `<article class="brief-item priority-${esc(x.priority)}"><div><span class="brief-module">${esc(x.module)}</span><strong>${esc(x.title)}</strong><p>${esc(x.detail)}</p></div>${go}</article>`}
function briefSection(title,items,kind){if(!items||!items.length)return '';return `<section class="brief-section ${esc(kind)}"><h4>${esc(title)} <span>${items.length}</span></h4>${items.map(briefItem).join('')}</section>`}
async function loadCommandBrief(){try{const x=await apiCall('/api/control/brief');$('briefHeadline').textContent=x.headline;$('briefGenerated').textContent='Updated '+new Date(x.generated_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});$('briefCritical').textContent=x.counts.critical;$('briefAction').textContent=x.counts.action;$('briefOpportunities').textContent=x.counts.opportunities;$('briefInfo').textContent=x.counts.info;const state=$('briefState');state.textContent=x.status==='caught_up'?'CAUGHT UP':x.status.replaceAll('_',' ').toUpperCase();state.className='status-pill brief-state-'+x.status;const sec=x.sections||{};$('briefOutput').innerHTML=briefSection('CRITICAL',sec.critical,'critical')+briefSection('ACTION REQUIRED',sec.action,'action')+briefSection('OPPORTUNITIES',sec.opportunities,'opportunity')+briefSection('INFO',sec.info,'info')+(x.caught_up&&!sec.opportunities?.length?'<div class="brief-caught-up"><strong>✓ PITMARK IS CAUGHT UP</strong><span>No approvals, security issues or campaign actions need you right now.</span></div>':'')}catch(e){$('briefOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
function renderShieldStatus(st){const c=st.controls||{};const labels={signed_control_sessions:'Signed admin sessions',security_headers:'Security headers',rate_limiting:'Rate limiting',request_size_limits:'Request size limits',device_id_validation:'Device identity validation',discord_signature_verification:'Discord request verification',oauth_tokens_encrypted_at_rest:'OAuth token encryption',persistent_database:'Persistent database'};$('shieldSecurityStatus').innerHTML=Object.entries(labels).map(([k,label])=>`<div class="shield-control"><span>${esc(label)}</span><strong class="${c[k]?'ok':'warn'}">${c[k]?'ACTIVE':'ATTENTION'}</strong></div>`).join('');const overall=$('shieldOverall');overall.textContent=(st.overall||'attention').toUpperCase();overall.className='status-pill '+(st.overall==='healthy'?'status-approved':'status-pending');$('shieldMailboxStatus').textContent=st.communications?.mailbox_connected?'Production mailbox connected to Shield.':'Communications Protection: production mailbox not connected yet. Classification engine is ready; synthetic test events stay hidden from production queues.'}
function shieldCard(x){return `<article class="record-card shield-card"><div class="record-row"><span class="status-pill shield-${esc((x.classification||'review').toLowerCase())}">${esc(x.classification)}</span><strong>${esc(x.subject||'(no subject)')}</strong></div><span>${esc(x.sender)}</span><small>${Math.round((x.confidence||0)*100)}% confidence · ${x.protected?'protected':'standard'} · action: ${esc(x.action_taken||'none')}</small><small>${esc((x.reasons||[]).join(' · '))}</small></article>`}
async function loadShield(){try{const f=$('shieldFilter').value;const url='/api/control/shield/events'+(f?'?classification='+encodeURIComponent(f):'');const [items,st,audit]=await Promise.all([apiCall(url),apiCall('/api/control/shield/status'),apiCall('/api/control/shield/audit')]);$('shieldAuditOutput').innerHTML=audit.length?audit.map(x=>`<article class="record-card"><div class="record-row"><strong>${esc((x.event_type||'security event').replaceAll('_',' '))}</strong><span class="status-pill">${esc(x.severity||'info')}</span></div><span>${esc(x.actor||'system')}</span><small>${esc(x.detail||'')} · ${new Date(x.created_at).toLocaleString()}</small></article>`).join(''):'<div class="empty-state"><strong>No security audit events yet.</strong><span>Shield will record account and administrative security events here.</span></div>';$('shieldOutput').innerHTML=items.length?items.map(shieldCard).join(''):'<div class="empty-state"><strong>No messages currently require review.</strong><span>Synthetic test messages are kept out of production queues.</span></div>';renderShieldStatus(st)}catch(e){$('shieldOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function runShieldTest(){const b=$('shieldTestBtn'),m=$('shieldTestResult');b.disabled=true;m.textContent=' Running synthetic messages…';try{const x=await apiCall('/api/control/shield/test',{method:'POST',body:JSON.stringify({clear_previous_tests:true})});const counts={};x.created.forEach(v=>counts[v.classification]=(counts[v.classification]||0)+1);m.textContent=` PASS — Legit ${counts.Legit||0} · Review ${counts.Review||0} · Spam ${counts.Spam||0} · System ${counts.System||0}`;$('shieldFilter').value='';await loadShield();await loadStatus()}catch(e){m.textContent=' ERROR — '+e.message}finally{b.disabled=false}}
const methods=['discord','email','facebook','instagram','website','other'];
const stages=['prospect','contacted','interested','partner','supporter'];
const supporters=['unverified','verified','supporter','partner'];
function opts(list,current){return list.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v}</option>`).join('')}
function outreachCard(o){return `<article class="record-card outreach-card" data-id="${o.id}"><div class="record-row"><strong>${esc(o.name)}</strong><span class="status-pill status-${esc(o.stage)}">${esc(o.stage)}</span></div><span>${esc(o.organization||'')}</span><div class="outreach-edit"><select class="select omethod">${opts(methods,o.contact_type)}</select><input class="input ocontact" value="${esc(o.email||'')}" placeholder="Handle / email / URL"><select class="select ostage">${opts(stages,o.stage)}</select><select class="select osupport">${opts(supporters,o.supporter_status)}</select><input class="input ofollow" type="date" value="${esc((o.next_follow_up||'').slice(0,10))}"><input class="input onotes" value="${esc(o.notes||'')}" placeholder="Notes"><button class="btn secondary mini" data-outreach-save>Save</button></div></article>`}
async function addOutreach(){try{await apiCall('/api/control/outreach',{method:'POST',body:JSON.stringify({name:$('oname').value,organization:$('oorg').value||null,contact_type:$('omethod').value,email:$('ocontact').value||null,stage:$('ostage').value})});$('oname').value='';$('oorg').value='';$('ocontact').value='';loadOutreach();loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
async function loadOutreach(){try{const items=await apiCall('/api/control/outreach');$('outreachOutput').innerHTML=items.length?items.map(outreachCard).join(''):'<div class="empty-state">Nothing here yet.</div>'}catch(e){$('outreachOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function saveOutreach(card){const id=card.dataset.id;const body={contact_type:card.querySelector('.omethod').value,email:card.querySelector('.ocontact').value||null,stage:card.querySelector('.ostage').value,supporter_status:card.querySelector('.osupport').value,next_follow_up:card.querySelector('.ofollow').value||null,notes:card.querySelector('.onotes').value||null};try{await apiCall('/api/control/outreach/'+id,{method:'PATCH',body:JSON.stringify(body)});await loadOutreach()}catch(e){showToast('Action Failed',e.message,'error')}}
async function generateBlog(){const b=$('generateBlogBtn');b.disabled=true;b.textContent='Generating…';try{const x=await apiCall('/api/control/blog/generate',{method:'POST',body:JSON.stringify({subject:$('bsubject').value,content_type:$('btype').value,notes:$('bnotes').value||null})});$('btitle').value=x.title;$('bbody').value=x.body_html}catch(e){showToast('Action Failed',e.message,'error')}finally{b.disabled=false;b.textContent='Generate Draft'}}
async function addBlog(){try{await apiCall('/api/control/blog/drafts',{method:'POST',body:JSON.stringify({title:$('btitle').value,body_html:$('bbody').value,content_type:$('btype').value})});$('btitle').value='';$('bbody').value='';loadBlog();loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
function blogCard(b){const canSchedule=['draft','approved'].includes(b.status);const publish=b.status==='approved'?'<button class="btn mini" data-blog-action="shopify-publish">Publish to Shopify</button>':'';return `<article class="record-card blog-card" data-id="${b.id}"><div class="record-row"><span class="status-pill status-${esc(b.status)}">${esc(b.status)}</span><strong>${esc(b.title)}</strong></div><span>${esc(b.content_type)}</span><div class="queue-body blog-preview">${esc(b.body_html)}</div><div class="queue-actions">${b.status==='draft'?'<button class="btn mini" data-blog-action="approve">Approve</button>':''}${b.status!=='published'?'<button class="btn secondary mini" data-blog-action="reject">Reject</button>':''}${canSchedule?'<input class="input schedule-input" type="datetime-local"><button class="btn secondary mini" data-blog-action="schedule">Schedule</button>':''}${b.status!=='published'?'<button class="btn ghost mini" data-blog-action="archive">Archive</button>':''}${publish}</div></article>`}
async function loadBlog(){try{const items=await apiCall('/api/control/blog/drafts');$('blogOutput').innerHTML=items.length?items.map(blogCard).join(''):'<div class="empty-state">Nothing here yet.</div>'}catch(e){$('blogOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function blogAction(card,action){try{if(action==='shopify-publish'){const btn=card.querySelector('[data-blog-action="shopify-publish"]');if(btn){btn.disabled=true;btn.textContent='Publishing…'}const x=await apiCall(`/api/control/blog/drafts/${card.dataset.id}/shopify-publish`,{method:'POST'});showToast('SHOPIFY PUBLISHED',x.shopify?.title||'Article published','success');loadBlog();loadStatus();return}const payload={action};if(action==='schedule'){const input=card.querySelector('.schedule-input');if(!input.value){input.focus();return}payload.scheduled_for=input.value}await apiCall(`/api/control/blog/drafts/${card.dataset.id}/decision`,{method:'POST',body:JSON.stringify(payload)});loadBlog();loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
async function loadConnections(){try{const base=await apiCall('/api/control/settings/connections');const social=await loadSocialPublishStatus();for(const name of ['facebook','instagram','tiktok','x']){const el=$('conn-'+name);if(!el)continue;let connected=Boolean(base?.[name]?.connected),ready=Boolean(base?.[name]?.ready);if(name==='facebook')connected=Boolean(social?.facebook?.configured);if(name==='instagram')connected=Boolean(social?.instagram?.configured);if(name==='x')connected=Boolean(social?.x?.configured);el.textContent=connected?'Connected':(ready?'Ready to authorize':'Setup required');el.className=connected?'connected':(ready?'ready':'')}}catch(e){console.error(e)}}
async function logout(){await apiCall('/api/control/auth/logout',{method:'POST'});location.href='/control'}
async function changePassword(){const cur=$('currentPassword').value,n=$('newPassword').value,c=$('confirmPassword').value,msg=$('securityMessage');msg.textContent='';if(n!==c){msg.textContent='New passwords do not match.';return}try{await apiCall('/api/control/auth/change-password',{method:'POST',body:JSON.stringify({current_password:cur,new_password:n})});msg.textContent='Password changed. Sign in again…';setTimeout(()=>location.href='/control',700)}catch(e){msg.textContent=e.message}}
function rookieCard(r){const stages=['prospect','interested','intake_sent','submitted','verification','ready_for_review','selected','story_building','racer_review','scheduled','published','alumni'];return `<article class="record-card rookie-card" data-id="${r.id}"><div class="record-row"><strong>${esc(r.name)}</strong><span class="status-pill">${esc(r.stage)}</span></div><div class="meta"><span>Intake: ${esc(r.intake_status)}</span><span>Verification: ${esc(r.verification_status)}</span><span>Media: ${esc(r.media_permission)}</span><span>Guardian: ${esc(r.guardian_status)}</span>${r.research_job?`<span class="research-chip">Research ${esc(r.research_job.status)} · Job #${r.research_job.id}</span>`:''}</div><div class="outreach-fields"><select class="select" data-ry-stage>${stages.map(x=>`<option value="${x}" ${x===r.stage?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select><select class="select" data-ry-intake><option value="not_sent" ${r.intake_status==='not_sent'?'selected':''}>Intake not sent</option><option value="sent" ${r.intake_status==='sent'?'selected':''}>Intake sent</option><option value="received" ${r.intake_status==='received'?'selected':''}>Intake received</option></select><select class="select" data-ry-media><option value="pending" ${r.media_permission==='pending'?'selected':''}>Media pending</option><option value="approved" ${r.media_permission==='approved'?'selected':''}>Media approved</option></select><button class="btn secondary mini" data-ry-save>Save</button><button class="btn mini" data-ry-research data-entity="${r.entity_id}">Research & Prepare</button></div></article>`}
async function loadRookies(){try{const x=await apiCall('/api/control/campaigns/rookie-year');const a=x.participants||[];$('rookieOutput').innerHTML=a.length?a.map(rookieCard).join(''):'<div class="empty-state">No Rookie Year participants yet.</div>';$('ryInterested').textContent=a.filter(x=>x.stage==='interested').length;$('rySent').textContent=a.filter(x=>['sent','received'].includes(x.intake_status)).length;$('ryReady').textContent=a.filter(x=>['ready_for_review','selected','story_building'].includes(x.stage)).length;$('ryPublished').textContent=a.filter(x=>['published','alumni'].includes(x.stage)).length}catch(e){$('rookieOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function addRookie(){try{await apiCall('/api/control/campaigns/rookie-year/participants',{method:'POST',body:JSON.stringify({name:$('ryName').value,community_lane:$('ryLane').value,stage:$('ryStage').value,intake_status:$('ryStage').value==='intake_sent'?'sent':'not_sent'})});$('ryName').value='';loadRookies()}catch(e){showToast('Action Failed',e.message,'error')}}
async function rookieAction(e){const save=e.target.closest('[data-ry-save]'),research=e.target.closest('[data-ry-research]');if(save){const c=save.closest('.rookie-card');await apiCall('/api/control/campaigns/rookie-year/participants/'+c.dataset.id,{method:'POST',body:JSON.stringify({stage:c.querySelector('[data-ry-stage]').value,intake_status:c.querySelector('[data-ry-intake]').value,media_permission:c.querySelector('[data-ry-media]').value})});loadRookies()}if(research){try{research.disabled=true;research.textContent='Queuing…';const x=await apiCall('/api/control/community/research/prepare',{method:'POST',body:JSON.stringify({entity_id:Number(research.dataset.entity),research_type:'rookie_deep_dive'})});showToast('Research Job Queued ✓',x.subject+' · Job #'+x.job_id+' · No outreach will be sent without approval.');await loadRookies()}catch(err){showToast('Research Job Failed',err.message,'error')}finally{research.disabled=false;research.textContent='Research & Prepare'}}}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));document.addEventListener('click',e=>{const b=e.target.closest('[data-brief-go]');if(b)setView(b.dataset.briefGo)});
$('logoutBtn').addEventListener('click',logout);$('refreshDashboardBtn').addEventListener('click',loadStatus);$('generateBtn').addEventListener('click',composePost);$('savePostBtn').addEventListener('click',savePost);$('refreshQueueBtn').addEventListener('click',loadQueue);$('runIntelBtn').addEventListener('click',runIntelligence);$('queueFilter').addEventListener('change',loadQueue);$('queueList').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)queueAction(b.closest('.queue-card'),b.dataset.action)});
$('shieldBtn').addEventListener('click',loadShield);$('shieldFilter').addEventListener('change',loadShield);$('shieldTestBtn').addEventListener('click',runShieldTest);
$('addRookieBtn').addEventListener('click',addRookie);$('loadRookiesBtn').addEventListener('click',loadRookies);$('rookieOutput').addEventListener('click',rookieAction);
$('addOutreachBtn').addEventListener('click',addOutreach);$('loadOutreachBtn').addEventListener('click',loadOutreach);$('outreachOutput').addEventListener('click',e=>{const b=e.target.closest('[data-outreach-save]');if(b)saveOutreach(b.closest('.outreach-card'))});
$('generateBlogBtn').addEventListener('click',generateBlog);$('addBlogBtn').addEventListener('click',addBlog);$('loadBlogBtn').addEventListener('click',loadBlog);$('blogOutput').addEventListener('click',e=>{const b=e.target.closest('[data-blog-action]');if(b)blogAction(b.closest('.blog-card'),b.dataset.blogAction)});
$('changePasswordBtn').addEventListener('click',changePassword);
$('platform').addEventListener('change',syncComposerPlatform);
document.querySelectorAll('input[name="igAssetMode"]').forEach(x=>x.addEventListener('change',syncAssetMode));
$('suggestAssetBtn').addEventListener('click',suggestInstagramAsset);
$('igUploadInput').addEventListener('change',()=>{const f=$('igUploadInput').files?.[0];uploadedInstagramUrl=null;if(!f){renderAssetPreview($('igUploadPreview'),null);return}if(f.size>6*1024*1024){$('composerMessage').textContent='Image must be 6 MB or smaller.';$('igUploadInput').value='';return}const url=URL.createObjectURL(f);renderAssetPreview($('igUploadPreview'),url,f.name)});
syncComposerPlatform();syncAssetMode();

(async()=>{try{await loadSession();setView(location.hash.replace('#','')||'dashboard')}catch(e){console.error(e)}})();

window.addEventListener('load',()=>{clearRookieAutofill();setTimeout(clearRookieAutofill,250);setTimeout(clearRookieAutofill,900)});

/* v0.12.4 Autopilot Research Agent */
rookieCard = function(r){
 const stages=['prospect','interested','intake_sent','submitted','verification','ready_for_review','selected','story_building','racer_review','scheduled','published','alumni'];
 const job=r.research_job;
 const jobStatus=job?String(job.status||'queued'):'none';
 const jobLabel=job?`Research ${esc(jobStatus)} · Job #${job.id}`:'';
 const view=job?`<button class="btn ghost mini" data-ry-view data-job="${job.id}">${jobStatus==='complete'?'View Research':'Check Research'}</button>`:'';
 return `<article class="record-card rookie-card" data-id="${r.id}"><div class="record-row"><strong>${esc(r.name)}</strong><span class="status-pill">${esc(r.stage)}</span></div><div class="meta"><span>Intake: ${esc(r.intake_status)}</span><span>Verification: ${esc(r.verification_status)}</span><span>Media: ${esc(r.media_permission)}</span><span>Guardian: ${esc(r.guardian_status)}</span>${job?`<span class="research-chip research-${esc(jobStatus)}">${jobLabel}</span>`:''}</div><div class="outreach-fields"><select class="select" data-ry-stage>${stages.map(x=>`<option value="${x}" ${x===r.stage?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select><select class="select" data-ry-intake><option value="not_sent" ${r.intake_status==='not_sent'?'selected':''}>Intake not sent</option><option value="sent" ${r.intake_status==='sent'?'selected':''}>Intake sent</option><option value="received" ${r.intake_status==='received'?'selected':''}>Intake received</option></select><select class="select" data-ry-media><option value="pending" ${r.media_permission==='pending'?'selected':''}>Media pending</option><option value="approved" ${r.media_permission==='approved'?'selected':''}>Media approved</option></select><button class="btn secondary mini" data-ry-save>Save</button><button class="btn mini" data-ry-research data-entity="${r.entity_id}">Research & Prepare</button>${view}</div><div class="research-detail" data-research-detail></div></article>`
}
function researchList(items,empty){if(!items||!items.length)return `<div class="research-empty">${esc(empty)}</div>`;return `<ul>${items.map(x=>`<li>${esc(typeof x==='string'?x:(x.claim||x.title||''))}</li>`).join('')}</ul>`}
async function showResearch(jobId,card){
 const box=card.querySelector('[data-research-detail]');
 box.classList.add('show');box.innerHTML='<div class="research-loading">AUTOPILOT RESEARCH AGENT · Loading…</div>';
 try{
  const x=await apiCall('/api/control/community/research/'+jobId),b=x.brief||{};
  const sources=(x.sources||b.sources||[]);
  const prep=x.outreach_prep;
  box.innerHTML=`<div class="research-head"><div><span class="eyebrow">AUTOPILOT RESEARCH AGENT</span><strong>${esc(b.subject||'Research Brief')}</strong></div><span class="status-pill status-${esc(x.status)}">${esc(x.status)}</span></div><div class="research-score-grid"><div><span>Completeness</span><strong>${Math.round(x.completeness||0)}%</strong></div><div><span>Verification</span><strong>${Math.round(x.verification_score||0)}%</strong></div><div><span>Identity</span><strong>${Math.round(b.identity_confidence||0)}%</strong></div><div><span>Sources</span><strong>${Number(b.source_count||sources.length||0)}</strong></div></div><div class="research-grid"><section><h4>WHAT WE KNOW</h4>${researchList(b.what_we_know,'No internal facts added yet.')}</section><section><h4>STRENGTHS</h4>${researchList(b.strengths,'No strong external identity evidence yet.')}</section><section><h4>GAPS / WEAKNESSES</h4>${researchList(b.weaknesses,'No major gaps flagged.')}</section><section><h4>AUTOPILOT RECOMMENDATION</h4><p>${esc(b.recommendation||x.recommended_action||'Research is still processing.')}</p></section></div><section class="research-sources"><h4>SOURCE LEDGER</h4>${sources.length?sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener"><span>${esc(s.title||s.url)}</span><small>${esc(s.source||'Public source')} · identity ${Math.round(s.identity_score||0)}%</small></a>`).join(''):'<div class="research-empty">No safe candidate sources found yet.</div>'}</section><div class="research-safety">${esc(b.safety_note||'Uncertain facts are not used as verified facts.')}</div><div class="research-actions">${x.status==='complete'?`<button class="btn secondary mini" data-ry-research-more data-job="${jobId}">Research More</button><button class="btn mini" data-outreach-prep data-job="${jobId}">${prep?'View Outreach Prep':'Prep Outreach'}</button>`:''}</div><div data-outreach-prep-box>${prep?renderOutreachPrep(prep):''}</div>`;
 }catch(err){box.innerHTML='<div class="error-box">'+esc(err.message)+'</div>'}
}

function outreachFactList(items,empty){if(!items||!items.length)return `<div class="research-empty">${esc(empty)}</div>`;return `<ul>${items.map(x=>`<li>${esc(typeof x==='string'?x:(x.claim||''))}${x.reason?`<small>${esc(x.reason)}</small>`:''}</li>`).join('')}</ul>`}
function renderOutreachPrep(p){return `<section class="outreach-prep-card"><div class="research-head"><div><span class="eyebrow">AUTOPILOT OUTREACH PREP</span><strong>Ready for Approval</strong></div><span class="status-pill status-approved">${esc(p.status||'ready_for_approval').replaceAll('_',' ')}</span></div><div class="outreach-prep-grid"><section><h4>WHY THIS MESSAGE</h4><p>${esc(p.why_message||'')}</p></section><section><h4>RECOMMENDED CHANNEL</h4><p>${esc(p.recommended_channel||'')}</p><h4>GOAL</h4><p>${esc(p.goal||'')}</p></section><section><h4>KNOWN FACTS USED</h4>${outreachFactList(p.facts_used,'No external facts are needed for this draft.')}</section><section><h4>FACTS EXCLUDED</h4>${outreachFactList(p.facts_excluded,'No excluded facts.')}</section></div><section class="outreach-message"><h4>MESSAGE DRAFT</h4><pre>${esc(p.draft_message||'')}</pre></section><div class="research-safety">Prepared only. Nothing has been sent. Human approval remains required before external contact.</div></section>`}

$('rookieOutput').addEventListener('click',async e=>{
 const view=e.target.closest('[data-ry-view]');if(view){e.preventDefault();e.stopPropagation();await showResearch(Number(view.dataset.job),view.closest('.rookie-card'));return}
 const more=e.target.closest('[data-ry-research-more]');if(more){e.preventDefault();e.stopPropagation();try{more.disabled=true;more.textContent='Queuing…';const x=await apiCall('/api/control/community/research/'+more.dataset.job+'/run',{method:'POST',body:'{}'});showToast('Research More Queued',`Job #${x.job_id} is running another verification pass.`,'info');setTimeout(loadRookies,2500)}catch(err){showToast('Research Failed',err.message,'error')}finally{more.disabled=false;more.textContent='Research More'}return}
 const prep=e.target.closest('[data-outreach-prep]');if(prep){e.preventDefault();e.stopPropagation();try{prep.disabled=true;prep.textContent='Preparing…';const x=await apiCall('/api/control/community/research/'+prep.dataset.job+'/outreach/prepare',{method:'POST',body:'{}'});const box=prep.closest('.research-detail').querySelector('[data-outreach-prep-box]');box.innerHTML=renderOutreachPrep(x);prep.textContent='View Outreach Prep';showToast('Outreach Prep Ready ✓',`${x.goal} · Nothing has been sent.`)}catch(err){showToast('Outreach Prep Failed',err.message,'error');prep.textContent='Prep Outreach'}finally{prep.disabled=false}return}
});
setInterval(()=>{const active=document.querySelector('[data-view-section="campaigns"].active');if(active&&[...document.querySelectorAll('.research-chip')].some(x=>/queued|researching|verifying/i.test(x.textContent)))loadRookies()},7000);

document.addEventListener('DOMContentLoaded',()=>{const b=$('refreshNotificationsBtn');if(b)b.addEventListener('click',loadNotifications);loadNotifications();});


/* v0.12.9 Ecosystem Autonomy Control Center */
function autonomyLabel(x){return String(x||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function loadAutonomy(){const boxes=[$('autonomyOutput'),$('autonomySettingsOutput')].filter(Boolean);if(!boxes.length)return;try{const x=await apiCall('/api/control/autonomy');const html=(x.policies||[]).map(p=>{const locked=p.safety_class==='red_zone';return `<article class="record-card autonomy-card" data-capability="${esc(p.capability)}"><div class="record-row"><div><strong>${esc(autonomyLabel(p.capability))}</strong><small>${esc(p.description||'')}</small></div><span class="status-pill">${esc(p.safety_class)}</span></div><div class="outreach-fields"><select class="select" data-autonomy-mode ${locked?'disabled':''}>${['off','approval','auto','human_only'].map(m=>`<option value="${m}" ${m===p.mode?'selected':''} ${locked&&m!=='human_only'?'disabled':''}>${esc(autonomyLabel(m))}</option>`).join('')}</select><button class="btn secondary mini" data-autonomy-save ${locked?'disabled':''}>Save</button></div>${locked?'<div class="research-safety">RED ZONE · Permanently HUMAN ONLY.</div>':''}</article>`}).join('');boxes.forEach(box=>box.innerHTML=html)}catch(err){boxes.forEach(box=>box.innerHTML='<div class="error-box">'+esc(err.message)+'</div>')}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-autonomy-save]');if(!b)return;const card=b.closest('.autonomy-card'),cap=card.dataset.capability,mode=card.querySelector('[data-autonomy-mode]').value;try{b.disabled=true;await apiCall('/api/control/autonomy/'+encodeURIComponent(cap),{method:'PATCH',body:JSON.stringify({mode})});showToast('Autonomy Updated ✓',`${autonomyLabel(cap)} · ${autonomyLabel(mode)}`);await loadAutonomy()}catch(err){showToast('Autonomy Update Failed',err.message,'error')}finally{b.disabled=false}});


/* v0.13.0 Autopilot Planner */
function plannerTask(t){return `<article class="record-card"><div class="record-row"><strong>${esc(t.title)}</strong><span class="status-pill">${esc((t.priority||'normal').toUpperCase())}</span></div><small>${esc((t.kind||'task').replaceAll('_',' ').toUpperCase())}</small><span>${esc(t.why||'')}</span></article>`}
async function loadPlanner(){const box=$('plannerOutput');if(!box)return;try{const p=await apiCall('/api/control/autopilot/planner');box.innerHTML=`<article class="record-card"><strong>${esc(p.summary||'Pitmark plan')}</strong><small>${esc(p.principle||'Do useful work, not busy work.')}</small></article>${(p.tasks||[]).map(plannerTask).join('')}${(p.notes||[]).length?`<div class="note">${(p.notes||[]).map(esc).join(' · ')}</div>`:''}`}catch(err){box.innerHTML='<div class="error-box">'+esc(err.message)+'</div>'}}
async function runPlanner(){const b=$('runPlannerBtn');if(!b)return;try{b.disabled=true;b.textContent='Planning…';const p=await apiCall('/api/control/autopilot/planner/run',{method:'POST',body:'{}'});showToast('Pitmark Plan Updated ✓',p.summary||'Planner finished.');await loadPlanner()}catch(err){showToast('Planner Failed',err.message,'error')}finally{b.disabled=false;b.textContent='Build Plan'}}
document.addEventListener('DOMContentLoaded',()=>{const b=$('runPlannerBtn');if(b)b.addEventListener('click',runPlanner)});

function clearPhantomAutofill(){['ryName','oname','oorg','ocontact'].forEach(id=>{const el=$(id);if(!el)return;if(!el.dataset.userTouched){el.value='';setTimeout(()=>{if(!el.dataset.userTouched)el.value=''},80);el.addEventListener('input',()=>el.dataset.userTouched='1',{once:true})}})}
document.addEventListener('DOMContentLoaded',()=>{const brand=$('brandDashboardLink');if(brand)brand.addEventListener('click',e=>{e.preventDefault();setView('dashboard')});document.querySelectorAll('[data-stat-target]').forEach(card=>card.addEventListener('click',()=>setView(card.dataset.statTarget)));clearPhantomAutofill();setTimeout(clearPhantomAutofill,350)});
