
let pitmarkToastTimer;
function showToast(title,message,type='success'){const t=$('pitmarkToast');if(!t)return;t.className='pitmark-toast '+(['error','warning','info'].includes(type)?type:'');t.innerHTML=`<strong>${esc(title)}</strong><span>${esc(message)}</span>`;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(pitmarkToastTimer);pitmarkToastTimer=setTimeout(()=>t.classList.remove('show'),4200)}
let generated='';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function apiCall(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let data;try{data=JSON.parse(t)}catch{data=t}if(r.status===401){location.href='/control';throw new Error('Session expired.')}if(!r.ok)throw new Error((data&&data.detail)||t||('HTTP '+r.status));return data}
function setView(name){document.querySelectorAll('[data-view-section]').forEach(x=>x.classList.toggle('active',x.dataset.viewSection===name));function rookieCard(r){
 const stages=['prospect','interested','intake_sent','submitted','verification','ready_for_review','selected','story_building','racer_review','scheduled','published','alumni'];
 const job=r.research_job;
 const jobStatus=job?String(job.status||'queued'):'none';
 const jobLabel=job?`Research ${esc(jobStatus)} · Job #${job.id}`:'';
 const view=job?`<button class="btn ghost mini" data-ry-view data-job="${job.id}">${jobStatus==='complete'?'View Research':'Check Research'}</button>`:'';
 return `<article class="record-card rookie-card" data-id="${r.id}"><div class="record-row"><strong>${esc(r.name)}</strong><span class="status-pill">${esc(r.stage)}</span></div><div class="meta"><span>Intake: ${esc(r.intake_status)}</span><span>Verification: ${esc(r.verification_status)}</span><span>Media: ${esc(r.media_permission)}</span><span>Guardian: ${esc(r.guardian_status)}</span>${job?`<span class="research-chip research-${esc(jobStatus)}">${jobLabel}</span>`:''}</div><div class="outreach-fields"><select class="select" data-ry-stage>${stages.map(x=>`<option value="${x}" ${x===r.stage?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select><select class="select" data-ry-intake><option value="not_sent" ${r.intake_status==='not_sent'?'selected':''}>Intake not sent</option><option value="sent" ${r.intake_status==='sent'?'selected':''}>Intake sent</option><option value="received" ${r.intake_status==='received'?'selected':''}>Intake received</option></select><select class="select" data-ry-media><option value="pending" ${r.media_permission==='pending'?'selected':''}>Media pending</option><option value="approved" ${r.media_permission==='approved'?'selected':''}>Media approved</option></select><button class="btn secondary mini" data-ry-save>Save</button><button class="btn mini" data-ry-research data-entity="${r.entity_id}">Research & Prepare</button>${view}</div><div class="research-detail" data-research-detail></div></article>`
}
async function loadRookies(){try{const x=await apiCall('/api/control/campaigns/rookie-year');const a=x.participants||[];$('rookieOutput').innerHTML=a.length?a.map(rookieCard).join(''):'<div class="empty-state">No Rookie Year participants yet.</div>';$('ryInterested').textContent=a.filter(x=>x.stage==='interested').length;$('rySent').textContent=a.filter(x=>['sent','received'].includes(x.intake_status)).length;$('ryReady').textContent=a.filter(x=>['ready_for_review','selected','story_building'].includes(x.stage)).length;$('ryPublished').textContent=a.filter(x=>['published','alumni'].includes(x.stage)).length}catch(e){$('rookieOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function addRookie(){try{await apiCall('/api/control/campaigns/rookie-year/participants',{method:'POST',body:JSON.stringify({name:$('ryName').value,community_lane:$('ryLane').value,stage:$('ryStage').value,intake_status:$('ryStage').value==='intake_sent'?'sent':'not_sent'})});$('ryName').value='';loadRookies()}catch(e){showToast('Action Failed',e.message,'error')}}
async function rookieAction(e){const save=e.target.closest('[data-ry-save]'),research=e.target.closest('[data-ry-research]');if(save){const c=save.closest('.rookie-card');await apiCall('/api/control/campaigns/rookie-year/participants/'+c.dataset.id,{method:'POST',body:JSON.stringify({stage:c.querySelector('[data-ry-stage]').value,intake_status:c.querySelector('[data-ry-intake]').value,media_permission:c.querySelector('[data-ry-media]').value})});loadRookies()}if(research){try{research.disabled=true;research.textContent='Queuing…';const x=await apiCall('/api/control/community/research/prepare',{method:'POST',body:JSON.stringify({entity_id:Number(research.dataset.entity),research_type:'rookie_deep_dive'})});showToast('Research Job Queued ✓',x.subject+' · Job #'+x.job_id+' · No outreach will be sent without approval.');await loadRookies()}catch(err){showToast('Research Job Failed',err.message,'error')}finally{research.disabled=false;research.textContent='Research & Prepare'}}}
document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'instant'});if(name==='dashboard')loadStatus();if(name==='autopilot'){loadQueue();loadIntelligence()}if(name==='shield')loadShield();if(name==='campaigns')loadRookies();if(name==='outreach')loadOutreach();if(name==='blog')loadBlog();if(name==='settings'){loadConnections();loadAutonomy()}}
async function loadSession(){const me=await apiCall('/api/control/auth/me');$('sessionUser').textContent=(me.username||'admin').toUpperCase()}
async function loadStatus(){try{const x=await apiCall('/api/control/status');$('statPosts').textContent=x.social_pending;$('statShield').textContent=x.shield_review;$('statOutreach').textContent=x.outreach_contacts;$('statBlog').textContent=x.blog_drafts;await loadCommandBrief()}catch(e){console.error(e)}}
async function composePost(){try{const p=$('platform').value,g=$('goal').value,t=$('topic').value.trim();const x=await apiCall('/api/control/autopilot/composer/generate',{method:'POST',body:JSON.stringify({platform:p,goal:g,prompt:t||'Generate a useful Pitmark post',topic:t||null})});generated=x.body;$('draft').textContent=x.body+(x.visual_suggestion?'\n\nVISUAL: '+x.visual_suggestion:'');$('draft').classList.add('show')}catch(e){$('draft').textContent='ERROR: '+e.message;$('draft').classList.add('show')}}
async function savePost(){if(!generated)return;$('savePostBtn').disabled=true;try{const x=await apiCall('/api/control/autopilot/posts',{method:'POST',body:JSON.stringify({platform:$('platform').value,body:generated,content_type:$('goal').value,source:'manual'})});$('draft').textContent+='\n\nSaved as #'+x.id+' ('+x.status+')';await loadQueue();await loadStatus()}catch(e){$('draft').textContent+='\n\nSAVE ERROR: '+e.message}finally{$('savePostBtn').disabled=false}}
function queueCard(p){const when=p.scheduled_for?`<span>Scheduled: ${esc(p.scheduled_for)}</span>`:'';const canApprove=p.status==='pending';const canSchedule=['pending','approved'].includes(p.status);return `<article class="queue-card" data-id="${p.id}"><div class="queue-card-top"><div><span class="status-pill status-${esc(p.status)}">${esc(p.status)}</span><strong>#${p.id} · ${esc(p.platform)}</strong><span>${esc(p.content_type)} · ${esc(p.source)}</span>${when}</div><span>${esc((p.created_at||'').replace('T',' ').slice(0,16))}</span></div><div class="queue-body">${esc(p.body)}</div><div class="queue-actions">${canApprove?`<button class="btn mini" data-action="approve">Approve</button>`:''}<button class="btn secondary mini" data-action="reject">Reject</button>${canSchedule?`<input class="input schedule-input" type="datetime-local"><button class="btn secondary mini" data-action="schedule">Schedule</button>`:''}<button class="btn ghost mini" data-action="archive">Archive</button><button class="btn ghost mini" disabled title="Connect ${esc(p.platform)} first">Publish</button></div></article>`}
async function loadQueue(){try{const filter=$('queueFilter').value;const posts=await apiCall('/api/control/autopilot/posts'+(filter?'?status='+encodeURIComponent(filter):''));$('queueList').innerHTML=posts.length?posts.map(queueCard).join(''):'<div class="empty-state">No posts in this queue yet.</div>'}catch(e){$('queueList').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function queueAction(card,action){const id=card.dataset.id;const payload={action};if(action==='schedule'){const input=card.querySelector('.schedule-input');if(!input.value){input.focus();return}payload.scheduled_for=input.value}try{await apiCall(`/api/control/autopilot/posts/${id}/decision`,{method:'POST',body:JSON.stringify(payload)});await loadQueue();await loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
async function loadNotifications(){try{await apiCall('/api/control/notifications/sync',{method:'POST'});const data=await apiCall('/api/control/notifications');const items=data.items||[];const unread=items.filter(x=>x.status==='unread');$('notificationCount').textContent=unread.length+' unread';$('notificationOutput').innerHTML=unread.length?unread.slice(0,8).map(n=>`<article class="record-card" data-priority="${esc(n.priority)}"><strong>${esc(n.title)}</strong><span>${esc(n.module)} · ${esc(n.priority.toUpperCase())}</span><small>${esc(n.detail||'')}</small><small>WHY PITMARK NOTIFIED YOU · ${esc(n.reason||'Requires attention.')}</small><button class="btn secondary compact notification-read" data-id="${n.id}">Mark read</button></article>`).join(''):'<div class="empty-state">No notifications need you right now. Pitmark will keep opportunities bundled in the Command Brief.</div>';document.querySelectorAll('.notification-read').forEach(b=>b.onclick=async()=>{await apiCall('/api/control/notifications/'+b.dataset.id+'/read',{method:'POST'});loadNotifications()})}catch(e){$('notificationOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function loadIntelligence(){try{const st=await apiCall('/api/control/autopilot/intelligence/status');$('intelStatus').textContent=st.enabled?('AUTO · EVERY '+st.interval_hours+'H'):'DISABLED';if(st.last_run){const r=st.last_run;$('intelSummary').textContent=`Last scan ${r.status}: ${r.found} new signals found · ${r.queued} candidates queued${r.queued===0?' · nothing strong enough to add to the approval queue':''}.`}else{$('intelSummary').textContent='No intelligence scan has run yet.'}const ops=await apiCall('/api/control/autopilot/opportunities');const eng=await apiCall('/api/control/autopilot/opportunity-engine');const byId=Object.fromEntries((eng.opportunities||[]).map(x=>[x.opportunity_id,x]));$('opportunityList').innerHTML=ops.length?ops.slice(0,8).map(o=>{const e=byId[o.id];return `<article class="record-card"><strong>${esc(o.headline)}</strong><span>${e?'Opportunity '+e.score+'/100 · '+esc(e.recommended_action.replaceAll('_',' ')):esc(o.relevance)} · ${esc(o.reason||'')}</span>${e&&e.strengths.length?`<small>WHY PITMARK CARES · ${esc(e.strengths[0])}</small>`:''}${e&&e.weaknesses.length?`<small>WATCH · ${esc(e.weaknesses[0])}</small>`:''}${o.freshness?`<small>FRESHNESS · ${esc(o.freshness.status.toUpperCase())}${o.freshness.age_hours!=null?' · '+o.freshness.age_hours+'H OLD':''}</small>`:''}<a href="${esc(o.source_url)}" target="_blank" rel="noopener">Source ↗</a></article>`}).join(''):'<div class="empty-state">No opportunities yet. Run Intelligence Now.</div>'}catch(e){$('opportunityList').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function runIntelligence(){const b=$('runIntelBtn');b.disabled=true;b.textContent='Scanning…';try{const x=await apiCall('/api/control/autopilot/intelligence/run',{method:'POST'});$('intelSummary').textContent=`Scan complete — ${x.found} new signals found · ${x.queued} candidates queued${x.queued===0?' · nothing strong enough to queue':''}.`;await loadIntelligence();await loadQueue();await loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}finally{b.disabled=false;b.textContent='Run Intelligence Now'}}

function briefItem(x){const go=x.action_view?`<button class="btn ghost mini" data-brief-go="${esc(x.action_view)}">Open ${esc(x.module)}</button>`:'';return `<article class="brief-item priority-${esc(x.priority)}"><div><span class="brief-module">${esc(x.module)}</span><strong>${esc(x.title)}</strong><p>${esc(x.detail)}</p></div>${go}</article>`}
function briefSection(title,items,kind){if(!items||!items.length)return '';return `<section class="brief-section ${esc(kind)}"><h4>${esc(title)} <span>${items.length}</span></h4>${items.map(briefItem).join('')}</section>`}
async function loadCommandBrief(){try{const x=await apiCall('/api/control/brief');$('briefHeadline').textContent=x.headline;$('briefGenerated').textContent='Updated '+new Date(x.generated_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});$('briefCritical').textContent=x.counts.critical;$('briefAction').textContent=x.counts.action;$('briefOpportunities').textContent=x.counts.opportunities;$('briefInfo').textContent=x.counts.info;const state=$('briefState');state.textContent=x.status==='caught_up'?'CAUGHT UP':x.status.replaceAll('_',' ').toUpperCase();state.className='status-pill brief-state-'+x.status;const sec=x.sections||{};$('briefOutput').innerHTML=briefSection('CRITICAL',sec.critical,'critical')+briefSection('ACTION REQUIRED',sec.action,'action')+briefSection('OPPORTUNITIES',sec.opportunities,'opportunity')+briefSection('INFO',sec.info,'info')+(x.caught_up&&!sec.opportunities?.length?'<div class="brief-caught-up"><strong>✓ PITMARK IS CAUGHT UP</strong><span>No approvals, security issues or campaign actions need you right now.</span></div>':'')}catch(e){$('briefOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
function renderShieldStatus(st){const c=st.controls||{};const labels={signed_control_sessions:'Signed admin sessions',security_headers:'Security headers',rate_limiting:'Rate limiting',request_size_limits:'Request size limits',device_id_validation:'Device identity validation',discord_signature_verification:'Discord request verification',oauth_tokens_encrypted_at_rest:'OAuth token encryption',persistent_database:'Persistent database'};$('shieldSecurityStatus').innerHTML=Object.entries(labels).map(([k,label])=>`<div class="shield-control"><span>${esc(label)}</span><strong class="${c[k]?'ok':'warn'}">${c[k]?'ACTIVE':'ATTENTION'}</strong></div>`).join('');const overall=$('shieldOverall');overall.textContent=(st.overall||'attention').toUpperCase();overall.className='status-pill '+(st.overall==='healthy'?'status-approved':'status-pending');$('shieldMailboxStatus').textContent=st.communications?.mailbox_connected?'Production mailbox connected to Shield.':'Communications Protection: production mailbox not connected yet. Classification engine is ready; synthetic test events stay hidden from production queues.'}
function shieldCard(x){return `<article class="record-card shield-card"><div class="record-row"><span class="status-pill shield-${esc((x.classification||'review').toLowerCase())}">${esc(x.classification)}</span><strong>${esc(x.subject||'(no subject)')}</strong></div><span>${esc(x.sender)}</span><small>${Math.round((x.confidence||0)*100)}% confidence · ${x.protected?'protected':'standard'} · action: ${esc(x.action_taken||'none')}</small><small>${esc((x.reasons||[]).join(' · '))}</small></article>`}
async function loadShield(){try{const f=$('shieldFilter').value;const url='/api/control/shield/events'+(f?'?classification='+encodeURIComponent(f):'');const [items,st,audit]=await Promise.all([apiCall(url),apiCall('/api/control/shield/status'),apiCall('/api/control/shield/audit')]);$('shieldAuditOutput').innerHTML=audit.length?audit.map(x=>`<article class="record-card"><div class="record-row"><strong>${esc((x.event_type||'security event').replaceAll('_',' '))}</strong><span class="status-pill">${esc(x.severity||'info')}</span></div><span>${esc(x.actor||'system')}</span><small>${esc(x.detail||'')} · ${new Date(x.created_at).toLocaleString()}</small></article>`).join(''):'<div class="empty-state"><strong>No security audit events yet.</strong><span>Shield will record account and administrative security events here.</span></div>';$('shieldOutput').innerHTML=items.length?items.map(shieldCard).join(''):'<div class="empty-state"><strong>No messages currently require review.</strong><span>Synthetic test messages are kept out of production queues.</span></div>';renderShieldStatus(st)}catch(e){$('shieldOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function runShieldTest(){const b=$('shieldTestBtn'),m=$('shieldTestResult');b.disabled=true;m.textContent=' Running synthetic messages…';try{const x=await apiCall('/api/control/shield/test',{method:'POST',body:JSON.stringify({clear_previous_tests:true})});const counts={};x.created.forEach(v=>counts[v.classification]=(counts[v.classification]||0)+1);m.textContent=` PASS — Legit ${counts.Legit||0} · Review ${counts.Review||0} · Spam ${counts.Spam||0} · System ${counts.System||0}`;$('shieldFilter').value='';await loadShield();await loadStatus()}catch(e){m.textContent=' ERROR — '+e.message}finally{b.disabled=false}}
const methods=['discord','email','facebook','instagram','website','other'];
const stages=['prospect','contacted','interested','partner','supporter'];
const supporters=['unverified','verified','supporter','partner'];
function opts(list,current){return list.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v}</option>`).join('')}
function outreachCard(o){return `<article class="record-card outreach-card" data-id="${o.id}"><div class="record-row"><strong>${esc(o.name)}</strong><span class="status-pill status-${esc(o.stage)}">${esc(o.stage)}</span></div><span>${esc(o.organization||'')}</span><div class="outreach-edit"><select class="select omethod">${opts(methods,o.contact_type)}</select><input class="input ocontact" value="${esc(o.email||'')}" placeholder="Handle / email / URL"><select class="select ostage">${opts(stages,o.stage)}</select><select class="select osupport">${opts(supporters,o.supporter_status)}</select><input class="input ofollow" type="date" value="${esc((o.next_follow_up||'').slice(0,10))}"><input class="input onotes" value="${esc(o.notes||'')}" placeholder="Notes"><button class="btn secondary mini" data-outreach-save>Save</button></div></article>`}
async function addOutreach(){try{await apiCall('/api/control/outreach',{method:'POST',body:JSON.stringify({name:$('oname').value,organization:$('oorg').value||null,contact_type:$('omethod').value,email:$('ocontact').value||null,stage:$('ostage').value})});$('oname').value='';$('oorg').value='';$('ocontact').value='';loadOutreach();loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
async function loadOutreach(){try{const items=await apiCall('/api/control/outreach');$('outreachOutput').innerHTML=items.length?items.map(outreachCard).join(''):'<div class="empty-state">Nothing here yet.</div>'}catch(e){$('outreachOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function saveOutreach(card){const id=card.dataset.id;const body={contact_type:card.querySelector('.omethod').value,email:card.querySelector('.ocontact').value||null,stage:card.querySelector('.ostage').value,supporter_status:card.querySelector('.osupport').value,next_follow_up:card.querySelector('.ofollow').value||null,notes:card.querySelector('.onotes').value||null};try{await apiCall('/api/control/outreach/'+id,{method:'PATCH',body:JSON.stringify(body)});await loadOutreach()}catch(e){showToast('Action Failed',e.message,'error')}}
async function generateBlog(){const b=$('generateBlogBtn');b.disabled=true;b.textContent='Generating…';try{const x=await apiCall('/api/control/blog/generate',{method:'POST',body:JSON.stringify({subject:$('bsubject').value,content_type:$('btype').value,notes:$('bnotes').value||null})});$('btitle').value=x.title;$('bbody').value=x.body_html}catch(e){showToast('Action Failed',e.message,'error')}finally{b.disabled=false;b.textContent='Generate Draft'}}
async function addBlog(){try{await apiCall('/api/control/blog/drafts',{method:'POST',body:JSON.stringify({title:$('btitle').value,body_html:$('bbody').value,content_type:$('btype').value})});$('btitle').value='';$('bbody').value='';loadBlog();loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
function blogCard(b){const canSchedule=['draft','approved'].includes(b.status);return `<article class="record-card blog-card" data-id="${b.id}"><div class="record-row"><span class="status-pill status-${esc(b.status)}">${esc(b.status)}</span><strong>${esc(b.title)}</strong></div><span>${esc(b.content_type)}</span><div class="queue-body blog-preview">${esc(b.body_html)}</div><div class="queue-actions">${b.status==='draft'?'<button class="btn mini" data-blog-action="approve">Approve</button>':''}<button class="btn secondary mini" data-blog-action="reject">Reject</button>${canSchedule?'<input class="input schedule-input" type="datetime-local"><button class="btn secondary mini" data-blog-action="schedule">Schedule</button>':''}<button class="btn ghost mini" data-blog-action="archive">Archive</button><button class="btn ghost mini" disabled title="Connect Shopify publishing first">Publish</button></div></article>`}
async function loadBlog(){try{const items=await apiCall('/api/control/blog/drafts');$('blogOutput').innerHTML=items.length?items.map(blogCard).join(''):'<div class="empty-state">Nothing here yet.</div>'}catch(e){$('blogOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function blogAction(card,action){const payload={action};if(action==='schedule'){const input=card.querySelector('.schedule-input');if(!input.value){input.focus();return}payload.scheduled_for=input.value}try{await apiCall(`/api/control/blog/drafts/${card.dataset.id}/decision`,{method:'POST',body:JSON.stringify(payload)});loadBlog();loadStatus()}catch(e){showToast('Action Failed',e.message,'error')}}
async function loadConnections(){try{const x=await apiCall('/api/control/settings/connections');for(const [name,v] of Object.entries(x)){const el=$('conn-'+name);if(el){el.textContent=v.connected?'Connected':(v.ready?'Ready to authorize':'Setup required');el.className=v.connected?'connected':(v.ready?'ready':'')}}}catch(e){console.error(e)}}
async function logout(){await apiCall('/api/control/auth/logout',{method:'POST'});location.href='/control'}
async function changePassword(){const cur=$('currentPassword').value,n=$('newPassword').value,c=$('confirmPassword').value,msg=$('securityMessage');msg.textContent='';if(n!==c){msg.textContent='New passwords do not match.';return}try{await apiCall('/api/control/auth/change-password',{method:'POST',body:JSON.stringify({current_password:cur,new_password:n})});msg.textContent='Password changed. Sign in again…';setTimeout(()=>location.href='/control',700)}catch(e){msg.textContent=e.message}}
function rookieCard(r){const stages=['prospect','interested','intake_sent','submitted','verification','ready_for_review','selected','story_building','racer_review','scheduled','published','alumni'];return `<article class="record-card rookie-card" data-id="${r.id}"><div class="record-row"><strong>${esc(r.name)}</strong><span class="status-pill">${esc(r.stage)}</span></div><div class="meta"><span>Intake: ${esc(r.intake_status)}</span><span>Verification: ${esc(r.verification_status)}</span><span>Media: ${esc(r.media_permission)}</span><span>Guardian: ${esc(r.guardian_status)}</span>${r.research_job?`<span class="research-chip">Research ${esc(r.research_job.status)} · Job #${r.research_job.id}</span>`:''}</div><div class="outreach-fields"><select class="select" data-ry-stage>${stages.map(x=>`<option value="${x}" ${x===r.stage?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select><select class="select" data-ry-intake><option value="not_sent" ${r.intake_status==='not_sent'?'selected':''}>Intake not sent</option><option value="sent" ${r.intake_status==='sent'?'selected':''}>Intake sent</option><option value="received" ${r.intake_status==='received'?'selected':''}>Intake received</option></select><select class="select" data-ry-media><option value="pending" ${r.media_permission==='pending'?'selected':''}>Media pending</option><option value="approved" ${r.media_permission==='approved'?'selected':''}>Media approved</option></select><button class="btn secondary mini" data-ry-save>Save</button><button class="btn mini" data-ry-research data-entity="${r.entity_id}">Research & Prepare</button></div></article>`}
async function loadRookies(){try{const x=await apiCall('/api/control/campaigns/rookie-year');const a=x.participants||[];$('rookieOutput').innerHTML=a.length?a.map(rookieCard).join(''):'<div class="empty-state">No Rookie Year participants yet.</div>';$('ryInterested').textContent=a.filter(x=>x.stage==='interested').length;$('rySent').textContent=a.filter(x=>['sent','received'].includes(x.intake_status)).length;$('ryReady').textContent=a.filter(x=>['ready_for_review','selected','story_building'].includes(x.stage)).length;$('ryPublished').textContent=a.filter(x=>['published','alumni'].includes(x.stage)).length}catch(e){$('rookieOutput').innerHTML='<div class="error-box">'+esc(e.message)+'</div>'}}
async function addRookie(){try{await apiCall('/api/control/campaigns/rookie-year/participants',{method:'POST',body:JSON.stringify({name:$('ryName').value,community_lane:$('ryLane').value,stage:$('ryStage').value,intake_status:$('ryStage').value==='intake_sent'?'sent':'not_sent'})});$('ryName').value='';loadRookies()}catch(e){showToast('Action Failed',e.message,'error')}}
async function rookieAction(e){const save=e.target.closest('[data-ry-save]'),research=e.target.closest('[data-ry-research]');if(save){const c=save.closest('.rookie-card');await apiCall('/api/control/campaigns/rookie-year/participants/'+c.dataset.id,{method:'POST',body:JSON.stringify({stage:c.querySelector('[data-ry-stage]').value,intake_status:c.querySelector('[data-ry-intake]').value,media_permission:c.querySelector('[data-ry-media]').value})});loadRookies()}if(research){try{research.disabled=true;research.textContent='Queuing…';const x=await apiCall('/api/control/community/research/prepare',{method:'POST',body:JSON.stringify({entity_id:Number(research.dataset.entity),research_type:'rookie_deep_dive'})});showToast('Research Job Queued ✓',x.subject+' · Job #'+x.job_id+' · No outreach will be sent without approval.');await loadRookies()}catch(err){showToast('Research Job Failed',err.message,'error')}finally{research.disabled=false;research.textContent='Research & Prepare'}}}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));document.addEventListener('click',e=>{const b=e.target.closest('[data-brief-go]');if(b)setView(b.dataset.briefGo)});
$('logoutBtn').addEventListener('click',logout);$('refreshDashboardBtn').addEventListener('click',loadStatus);$('generateBtn').addEventListener('click',composePost);$('savePostBtn').addEventListener('click',savePost);$('refreshQueueBtn').addEventListener('click',loadQueue);$('runIntelBtn').addEventListener('click',runIntelligence);$('queueFilter').addEventListener('change',loadQueue);$('queueList').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)queueAction(b.closest('.queue-card'),b.dataset.action)});
$('shieldBtn').addEventListener('click',loadShield);$('shieldFilter').addEventListener('change',loadShield);$('shieldTestBtn').addEventListener('click',runShieldTest);
$('addRookieBtn').addEventListener('click',addRookie);$('loadRookiesBtn').addEventListener('click',loadRookies);$('rookieOutput').addEventListener('click',rookieAction);
$('addOutreachBtn').addEventListener('click',addOutreach);$('loadOutreachBtn').addEventListener('click',loadOutreach);$('outreachOutput').addEventListener('click',e=>{const b=e.target.closest('[data-outreach-save]');if(b)saveOutreach(b.closest('.outreach-card'))});
$('generateBlogBtn').addEventListener('click',generateBlog);$('addBlogBtn').addEventListener('click',addBlog);$('loadBlogBtn').addEventListener('click',loadBlog);$('blogOutput').addEventListener('click',e=>{const b=e.target.closest('[data-blog-action]');if(b)blogAction(b.closest('.blog-card'),b.dataset.blogAction)});
$('changePasswordBtn').addEventListener('click',changePassword);
(async()=>{try{await loadSession();setView(location.hash.replace('#','')||'dashboard')}catch(e){console.error(e)}})();

window.addEventListener('load',()=>{clearRookieAutofill();setTimeout(clearRookieAutofill,250);setTimeout(clearRookieAutofill,900)});

/* v0.12.4 Autopilot Research Agent */
rookieCard = function(r){
 const stages=['prospect','interested','intake_sent','submitted','verification','ready_for_review','selected','story_building','racer_review','scheduled','published','alumni'];
 const job=r.research_job;
 const jobStatus=job?String(job.status||'queued'):'none';
 const jobLabel=job?`Research ${esc(jobStatus)} · Job #${job.id}`:'';
 const view=job?`<button class="btn ghost mini" data-ry-view data-job="${job.id}">${jobStatus==='complete'?'View Research':'Check Research'}</button>`:'';
 return `<article class="record-card rookie-card" data-id="${r.id}"><div class="record-row"><strong>${esc(r.name)}</strong><span class="status-pill">${esc(r.stage)}</span></div><div class="meta"><span>Intake: ${esc(r.intake_status)}</span><span>Verification: ${esc(r.verification_status)}</span><span>Media: ${esc(r.media_permission)}</span><span>Guardian: ${esc(r.guardian_status)}</span>${job?`<span class="research-chip research-${esc(jobStatus)}">${jobLabel}</span>`:''}</div><div class="outreach-fields"><select class="select" data-ry-stage>${stages.map(x=>`<option value="${x}" ${x===r.stage?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select><select class="select" data-ry-intake><option value="not_sent" ${r.intake_status==='not_sent'?'selected':''}>Intake not sent</option><option value="sent" ${r.intake_status==='sent'?'selected':''}>Intake sent</option><option value="received" ${r.intake_status==='received'?'selected':''}>Intake received</option></select><select class="select" data-ry-media><option value="pending" ${r.media_permission==='pending'?'selected':''}>Media pending</option><option value="approved" ${r.media_permission==='approved'?'selected':''}>Media approved</option></select><button class="btn secondary mini" data-ry-save>Save</button><button class="btn mini" data-ry-research data-entity="${r.entity_id}">Research & Prepare</button>${view}</div><div class="research-detail" data-research-detail></div></article>`
}
function researchList(items,empty){if(!items||!items.length)return `<div class="research-empty">${esc(empty)}</div>`;return `<ul>${items.map(x=>`<li>${esc(typeof x==='string'?x:(x.claim||x.title||''))}</li>`).join('')}</ul>`}
async function showResearch(jobId,card){
 const box=card.querySelector('[data-research-detail]');
 box.classList.add('show');box.innerHTML='<div class="research-loading">AUTOPILOT RESEARCH AGENT · Loading…</div>';
 try{
  const x=await apiCall('/api/control/community/research/'+jobId),b=x.brief||{};
  const sources=(x.sources||b.sources||[]);
  const prep=x.outreach_prep;
  box.innerHTML=`<div class="research-head"><div><span class="eyebrow">AUTOPILOT RESEARCH AGENT</span><strong>${esc(b.subject||'Research Brief')}</strong></div><span class="status-pill status-${esc(x.status)}">${esc(x.status)}</span></div><div class="research-score-grid"><div><span>Completeness</span><strong>${Math.round(x.completeness||0)}%</strong></div><div><span>Verification</span><strong>${Math.round(x.verification_score||0)}%</strong></div><div><span>Identity</span><strong>${Math.round(b.identity_confidence||0)}%</strong></div><div><span>Sources</span><strong>${Number(b.source_count||sources.length||0)}</strong></div></div><div class="research-grid"><section><h4>WHAT WE KNOW</h4>${researchList(b.what_we_know,'No internal facts added yet.')}</section><section><h4>STRENGTHS</h4>${researchList(b.strengths,'No strong external identity evidence yet.')}</section><section><h4>GAPS / WEAKNESSES</h4>${researchList(b.weaknesses,'No major gaps flagged.')}</section><section><h4>AUTOPILOT RECOMMENDATION</h4><p>${esc(b.recommendation||x.recommended_action||'Research is still processing.')}</p></section></div><section class="research-sources"><h4>SOURCE LEDGER</h4>${sources.length?sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener"><span>${esc(s.title||s.url)}</span><small>${esc(s.source||'Public source')} · identity ${Math.round(s.identity_score||0)}%</small></a>`).join(''):'<div class="research-empty">No safe candidate sources found yet.</div>'}</section><div class="research-safety">${esc(b.safety_note||'Uncertain facts are not used as verified facts.')}</div><div class="research-actions">${x.status==='complete'?`<button class="btn secondary mini" data-ry-research-more data-job="${jobId}">Research More</button><button class="btn mini" data-outreach-prep data-job="${jobId}">${prep?'View Outreach Prep':'Prep Outreach'}</button>`:''}</div><div data-outreach-prep-box>${prep?renderOutreachPrep(prep):''}</div>`;
 }catch(err){box.innerHTML='<div class="error-box">'+esc(err.message)+'</div>'}
}

function outreachFactList(items,empty){if(!items||!items.length)return `<div class="research-empty">${esc(empty)}</div>`;return `<ul>${items.map(x=>`<li>${esc(typeof x==='string'?x:(x.claim||''))}${x.reason?`<small>${esc(x.reason)}</small>`:''}</li>`).join('')}</ul>`}
function renderOutreachPrep(p){return `<section class="outreach-prep-card"><div class="research-head"><div><span class="eyebrow">AUTOPILOT OUTREACH PREP</span><strong>Ready for Approval</strong></div><span class="status-pill status-approved">${esc(p.status||'ready_for_approval').replaceAll('_',' ')}</span></div><div class="outreach-prep-grid"><section><h4>WHY THIS MESSAGE</h4><p>${esc(p.why_message||'')}</p></section><section><h4>RECOMMENDED CHANNEL</h4><p>${esc(p.recommended_channel||'')}</p><h4>GOAL</h4><p>${esc(p.goal||'')}</p></section><section><h4>KNOWN FACTS USED</h4>${outreachFactList(p.facts_used,'No external facts are needed for this draft.')}</section><section><h4>FACTS EXCLUDED</h4>${outreachFactList(p.facts_excluded,'No excluded facts.')}</section></div><section class="outreach-message"><h4>MESSAGE DRAFT</h4><pre>${esc(p.draft_message||'')}</pre></section><div class="research-safety">Prepared only. Nothing has been sent. Human approval remains required before external contact.</div></section>`}

$('rookieOutput').addEventListener('click',async e=>{
 const view=e.target.closest('[data-ry-view]');if(view){e.preventDefault();e.stopPropagation();await showResearch(Number(view.dataset.job),view.closest('.rookie-card'));return}
 const more=e.target.closest('[data-ry-research-more]');if(more){e.preventDefault();e.stopPropagation();try{more.disabled=true;more.textContent='Queuing…';const x=await apiCall('/api/control/community/research/'+more.dataset.job+'/run',{method:'POST',body:'{}'});showToast('Research More Queued',`Job #${x.job_id} is running another verification pass.`,'info');setTimeout(loadRookies,2500)}catch(err){showToast('Research Failed',err.message,'error')}finally{more.disabled=false;more.textContent='Research More'}return}
 const prep=e.target.closest('[data-outreach-prep]');if(prep){e.preventDefault();e.stopPropagation();try{prep.disabled=true;prep.textContent='Preparing…';const x=await apiCall('/api/control/community/research/'+prep.dataset.job+'/outreach/prepare',{method:'POST',body:'{}'});const box=prep.closest('.research-detail').querySelector('[data-outreach-prep-box]');box.innerHTML=renderOutreachPrep(x);prep.textContent='View Outreach Prep';showToast('Outreach Prep Ready ✓',`${x.goal} · Nothing has been sent.`)}catch(err){showToast('Outreach Prep Failed',err.message,'error');prep.textContent='Prep Outreach'}finally{prep.disabled=false}return}
});
setInterval(()=>{const active=document.querySelector('[data-view-section="campaigns"].active');if(active&&[...document.querySelectorAll('.research-chip')].some(x=>/queued|researching|verifying/i.test(x.textContent)))loadRookies()},7000);

document.addEventListener('DOMContentLoaded',()=>{const b=$('refreshNotificationsBtn');if(b)b.addEventListener('click',loadNotifications);loadNotifications();});


/* v0.12.9 Ecosystem Autonomy Control Center */
function autonomyLabel(x){return String(x||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function loadAutonomy(){const box=$('autonomyOutput');if(!box)return;try{const x=await apiCall('/api/control/autonomy');box.innerHTML=(x.policies||[]).map(p=>{const locked=p.safety_class==='red_zone';return `<article class="record-card autonomy-card" data-capability="${esc(p.capability)}"><div class="record-row"><div><strong>${esc(autonomyLabel(p.capability))}</strong><small>${esc(p.description||'')}</small></div><span class="status-pill">${esc(p.safety_class)}</span></div><div class="outreach-fields"><select class="select" data-autonomy-mode ${locked?'disabled':''}>${['off','approval','auto','human_only'].map(m=>`<option value="${m}" ${m===p.mode?'selected':''} ${locked&&m!=='human_only'?'disabled':''}>${esc(autonomyLabel(m))}</option>`).join('')}</select><button class="btn secondary mini" data-autonomy-save ${locked?'disabled':''}>Save</button></div>${locked?'<div class="research-safety">RED ZONE · Permanently HUMAN ONLY.</div>':''}</article>`}).join('')}catch(err){box.innerHTML='<div class="error-box">'+esc(err.message)+'</div>'}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-autonomy-save]');if(!b)return;const card=b.closest('.autonomy-card'),cap=card.dataset.capability,mode=card.querySelector('[data-autonomy-mode]').value;try{b.disabled=true;await apiCall('/api/control/autonomy/'+encodeURIComponent(cap),{method:'PATCH',body:JSON.stringify({mode})});showToast('Autonomy Updated ✓',`${autonomyLabel(cap)} · ${autonomyLabel(mode)}`);await loadAutonomy()}catch(err){showToast('Autonomy Update Failed',err.message,'error')}finally{b.disabled=false}});
