from fastapi import APIRouter
from fastapi.responses import HTMLResponse
router=APIRouter()
HTML=r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pitmark Control Center</title><style>
body{margin:0;background:#0d0f12;color:#f5f5f5;font:15px Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:22px}h1{color:#ff5500}.bar,.card{background:#171a1f;border:1px solid #2a2e35;border-radius:12px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.muted{color:#a8adb5}input,select,textarea,button{box-sizing:border-box;width:100%;background:#0f1216;color:white;border:1px solid #343944;border-radius:8px;padding:10px;margin:6px 0}button{background:#ff5500;border:0;font-weight:700;cursor:pointer}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}pre{white-space:pre-wrap;background:#0d0f12;padding:12px;border-radius:8px;min-height:80px}.pill{display:inline-block;padding:5px 8px;border-radius:999px;background:#252a31;margin-right:5px}</style></head><body><div class="wrap">
<h1>PITMARK CONTROL CENTER</h1><div class="muted">Autopilot + Shield + Outreach + Blog foundation</div>
<div class="bar"><label>Admin Key</label><input id="key" type="password" placeholder="X-Pitmark-Admin-Key"><button onclick="status()">Connect</button><pre id="status">Not connected.</pre></div>
<div class="grid"><div class="card"><h2>Manual Post Generator</h2><select id="platform"><option>facebook</option><option>instagram</option><option>tiktok</option><option>x</option></select><select id="goal"><option>community</option><option>education</option><option>entertainment</option><option>authority</option><option>product</option><option>partner</option></select><textarea id="topic" placeholder="What do you want to post about?"></textarea><button onclick="compose()">Generate</button><pre id="draft"></pre><button onclick="savePost()">Save to Approval Queue</button></div>
<div class="card"><h2>Pitmark Shield</h2><p class="muted">Classification history and Review queue live in Pitmark Cloud. Gmail connector can feed this API without giving the dashboard direct mailbox credentials.</p><button onclick="loadShield()">Load Review Queue</button><pre id="shield"></pre></div>
<div class="card"><h2>Track / Partner Outreach</h2><input id="oname" placeholder="Track / league / contact"><input id="oorg" placeholder="Organization"><input id="oemail" placeholder="Email"><button onclick="addOutreach()">Add Prospect</button><button onclick="loadOutreach()">Refresh Pipeline</button><pre id="outreach"></pre></div>
<div class="card"><h2>Shopify Blog / Track Spotlight</h2><input id="btitle" placeholder="Title"><textarea id="bbody" placeholder="Draft HTML / copy"></textarea><select id="btype"><option>article</option><option>track_spotlight</option><option>partner_spotlight</option></select><button onclick="addBlog()">Save Draft</button><button onclick="loadBlog()">Refresh Drafts</button><pre id="blog"></pre></div></div>
<script>
const H=()=>({'Content-Type':'application/json','X-Pitmark-Admin-Key':document.getElementById('key').value}); let generated='';
async function call(url,opt={}){opt.headers=H();let r=await fetch(url,opt);let t=await r.text();if(!r.ok)throw Error(t);try{return JSON.parse(t)}catch{return t}}
async function status(){try{document.getElementById('status').textContent=JSON.stringify(await call('/api/control/status'),null,2)}catch(e){document.getElementById('status').textContent=e}}
async function compose(){let p=document.getElementById('platform').value,g=document.getElementById('goal').value,t=document.getElementById('topic').value;let x=await call('/api/control/autopilot/composer/generate',{method:'POST',body:JSON.stringify({platform:p,goal:g,prompt:t||'Generate a useful Pitmark post',topic:t||null})});generated=x.body;document.getElementById('draft').textContent=x.body+(x.visual_suggestion?'\n\nVISUAL: '+x.visual_suggestion:'')}
async function savePost(){if(!generated)return;let x=await call('/api/control/autopilot/posts',{method:'POST',body:JSON.stringify({platform:document.getElementById('platform').value,body:generated,content_type:document.getElementById('goal').value})});document.getElementById('draft').textContent+='\n\nSaved as #'+x.id+' ('+x.status+')'}
async function loadShield(){document.getElementById('shield').textContent=JSON.stringify(await call('/api/control/shield/events?classification=Review'),null,2)}
async function addOutreach(){await call('/api/control/outreach',{method:'POST',body:JSON.stringify({name:document.getElementById('oname').value,organization:document.getElementById('oorg').value||null,email:document.getElementById('oemail').value||null})});loadOutreach()}
async function loadOutreach(){document.getElementById('outreach').textContent=JSON.stringify(await call('/api/control/outreach'),null,2)}
async function addBlog(){await call('/api/control/blog/drafts',{method:'POST',body:JSON.stringify({title:document.getElementById('btitle').value,body_html:document.getElementById('bbody').value,content_type:document.getElementById('btype').value})});loadBlog()}
async function loadBlog(){document.getElementById('blog').textContent=JSON.stringify(await call('/api/control/blog/drafts'),null,2)}
</script></div></body></html>'''
@router.get('/control',response_class=HTMLResponse,include_in_schema=False)
def control(): return HTML
