let generated='';
const $=id=>document.getElementById(id);
const H=()=>({'Content-Type':'application/json','X-Pitmark-Admin-Key':$('key').value.trim()});
function show(id,value){const el=$(id);el.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);el.classList.add('show')}
async function apiCall(url,opt={}){opt.headers={...(opt.headers||{}),...H()};const r=await fetch(url,opt);const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));try{return JSON.parse(t)}catch{return t}}
async function connectControlCenter(){const btn=$('connectBtn');btn.disabled=true;$('connectionText').textContent='Connecting…';try{await apiCall('/api/control/status');$('statusDot').className='status-dot good';$('connectionText').textContent='Connected';btn.classList.add('flash');show('draft','Control Center connected. Autopilot is ready.');setTimeout(()=>$('draft').classList.remove('show'),1400)}catch(e){$('statusDot').className='status-dot bad';$('connectionText').textContent='Connection failed';show('draft','CONNECT ERROR: '+e.message)}finally{btn.disabled=false}}
async function composePost(){try{const p=$('platform').value,g=$('goal').value,t=$('topic').value.trim();const x=await apiCall('/api/control/autopilot/composer/generate',{method:'POST',body:JSON.stringify({platform:p,goal:g,prompt:t||'Generate a useful Pitmark post',topic:t||null})});generated=x.body;show('draft',x.body+(x.visual_suggestion?'\n\nVISUAL: '+x.visual_suggestion:''))}catch(e){show('draft','GENERATOR ERROR: '+e.message)}}
async function savePost(){if(!generated){show('draft','Generate a post first.');return}try{const x=await apiCall('/api/control/autopilot/posts',{method:'POST',body:JSON.stringify({platform:$('platform').value,body:generated,content_type:$('goal').value})});show('draft',generated+'\n\nSaved as #'+x.id+' ('+x.status+')')}catch(e){show('draft','SAVE ERROR: '+e.message)}}
async function loadShield(){try{show('shieldOutput',await apiCall('/api/control/shield/events?classification=Review'))}catch(e){show('shieldOutput','SHIELD ERROR: '+e.message)}}
async function addOutreach(){try{await apiCall('/api/control/outreach',{method:'POST',body:JSON.stringify({name:$('oname').value,organization:$('oorg').value||null,email:$('oemail').value||null})});await loadOutreach()}catch(e){show('outreachOutput','OUTREACH ERROR: '+e.message)}}
async function loadOutreach(){try{show('outreachOutput',await apiCall('/api/control/outreach'))}catch(e){show('outreachOutput','OUTREACH ERROR: '+e.message)}}
async function addBlog(){try{await apiCall('/api/control/blog/drafts',{method:'POST',body:JSON.stringify({title:$('btitle').value,body_html:$('bbody').value,content_type:$('btype').value})});await loadBlog()}catch(e){show('blogOutput','BLOG ERROR: '+e.message)}}
async function loadBlog(){try{show('blogOutput',await apiCall('/api/control/blog/drafts'))}catch(e){show('blogOutput','BLOG ERROR: '+e.message)}}
window.addEventListener('DOMContentLoaded',()=>{
$('connectBtn').addEventListener('click',connectControlCenter);$('generateBtn').addEventListener('click',composePost);$('savePostBtn').addEventListener('click',savePost);$('shieldBtn').addEventListener('click',loadShield);$('addOutreachBtn').addEventListener('click',addOutreach);$('loadOutreachBtn').addEventListener('click',loadOutreach);$('addBlogBtn').addEventListener('click',addBlog);$('loadBlogBtn').addEventListener('click',loadBlog);$('key').addEventListener('keydown',e=>{if(e.key==='Enter')connectControlCenter()});
});
