(() => {
  const $pm=id=>document.getElementById(id);
  const escMail=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const parseList=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
  let mailFolder='inbox', mailReplyToMessageId=null, mailDraftId=null;

  function installEmailView(){
    const nav=document.getElementById('nav');
    if(nav&&!nav.querySelector('[data-view="email"]')){
      const b=document.createElement('button');b.dataset.view='email';b.innerHTML='<span class="ico">✉</span><span>Email<small>Inbox & Replies</small></span>';
      const blog=nav.querySelector('[data-view="blog"]');nav.insertBefore(b,blog||null);b.addEventListener('click',()=>window.setView('email'));
    }
    const content=document.querySelector('.content');
    if(content&&!document.querySelector('[data-view-section="email"]')){
      const s=document.createElement('section');s.className='view';s.dataset.viewSection='email';s.innerHTML=`
        <div class="view-heading"><div><h1>Email</h1><p>Pitmark's Cloud-owned inbox, sent mail and drafts.</p></div><button class="btn" id="mailComposeBtn">Compose</button></div>
        <section class="panel"><div class="panel-head queue-head"><div class="panel-icon">✉</div><div><h2>Pitmark Mail</h2><div class="meta"><span>Resend delivery</span><span>Shield-aware</span><span>Cloud-owned</span></div></div><span id="mailStatus" class="status-pill">Checking…</span></div><div class="mail-status-strip" id="mailStatusDetail"></div></section>
        <section class="panel" id="mailComposePanel" hidden><div class="panel-head"><div class="panel-icon">✎</div><div><h2>Compose</h2><div class="meta"><span id="mailComposeMode">New message</span></div></div></div><div class="mail-compose-grid"><input class="input wide" id="mailTo" placeholder="To — comma separated"><input class="input" id="mailCc" placeholder="CC"><input class="input" id="mailBcc" placeholder="BCC"><input class="input wide" id="mailSubject" placeholder="Subject"><textarea class="textarea wide" id="mailBody" rows="10" placeholder="Write your message…"></textarea></div><div class="approval"><button class="btn" id="mailSendBtn">Send</button><button class="btn secondary" id="mailDraftBtn">Save Draft</button><button class="btn ghost" id="mailCancelBtn">Cancel</button><span class="inline-message" id="mailComposeMessage"></span></div></section>
        <section class="panel"><div class="email-toolbar"><button class="btn secondary active" data-mail-folder="inbox">Inbox</button><button class="btn secondary" data-mail-folder="sent">Sent</button><button class="btn secondary" data-mail-folder="drafts">Drafts</button><button class="btn ghost" id="mailRefreshBtn">Refresh</button></div><div class="mail-shell"><div class="mail-list" id="mailList"><div class="mail-empty">Loading mail…</div></div><div class="mail-thread" id="mailThread"><div class="mail-empty">Select a conversation.</div></div></div></section>`;
      const directory=document.querySelector('[data-view-section="directory"]');content.insertBefore(s,directory||null);
    }
    wireEmailEvents();installArticleSourceBox();installRookieFlickerFix();
  }

  function wireEmailEvents(){
    $pm('mailComposeBtn')?.addEventListener('click',()=>openCompose());
    $pm('mailCancelBtn')?.addEventListener('click',closeCompose);
    $pm('mailSendBtn')?.addEventListener('click',sendMail);
    $pm('mailDraftBtn')?.addEventListener('click',saveDraft);
    $pm('mailRefreshBtn')?.addEventListener('click',loadMail);
    document.querySelectorAll('[data-mail-folder]').forEach(b=>b.addEventListener('click',()=>{mailFolder=b.dataset.mailFolder;document.querySelectorAll('[data-mail-folder]').forEach(x=>x.classList.toggle('active',x===b));loadMail()}));
    $pm('mailList')?.addEventListener('click',e=>{const row=e.target.closest('[data-mail-thread]');if(row)openThread(Number(row.dataset.mailThread));const draft=e.target.closest('[data-mail-draft]');if(draft)openDraft(JSON.parse(decodeURIComponent(draft.dataset.mailDraft)))});
    $pm('mailThread')?.addEventListener('click',e=>{const b=e.target.closest('[data-mail-reply]');if(b){const payload=JSON.parse(decodeURIComponent(b.dataset.mailReply));openCompose(payload)}});
  }

  async function loadMailStatus(){try{const x=await apiCall('/api/control/email/status');const ok=x.sending_configured;$pm('mailStatus').textContent=ok?'SEND READY':'SETUP REQUIRED';$pm('mailStatus').className='status-pill '+(ok?'status-approved':'status-pending');$pm('mailStatusDetail').innerHTML=`<span class="status-pill">${escMail(x.default_sender_address||x.default_sender||'')}</span><span class="status-pill">${escMail(x.mailbox_domain||'')}</span><span class="status-pill ${x.webhook_verification_configured?'status-approved':'status-pending'}">Inbound webhook ${x.webhook_verification_configured?'ready':'not connected yet'}</span>`}catch(e){$pm('mailStatus').textContent='ERROR';$pm('mailStatusDetail').textContent=e.message}}

  async function loadMail(){await loadMailStatus();const box=$pm('mailList');if(!box)return;box.innerHTML='<div class="mail-empty">Loading…</div>';try{const rows=await apiCall('/api/control/email/threads?folder='+encodeURIComponent(mailFolder));if(!rows.length){box.innerHTML='<div class="mail-empty">Nothing here yet.</div>';return}box.innerHTML=rows.map(x=>{const t=x.thread||{};const who=mailFolder==='inbox'?x.from:(x.to||[]).join(', ');const unread=Number(t.unread_count||0)>0&&mailFolder==='inbox';const preview=(x.text||'').replace(/\s+/g,' ').slice(0,110);const dt=x.created_at?new Date(x.created_at).toLocaleString():'';if(mailFolder==='drafts')return `<button class="mail-row" data-mail-draft="${encodeURIComponent(JSON.stringify(x))}"><strong>${escMail(x.subject||'(no subject)')}</strong><span>${escMail((x.to||[]).join(', ')||'No recipient')}</span><small>${escMail(preview||'Draft')} · ${escMail(dt)}</small></button>`;return `<button class="mail-row ${unread?'unread':''}" data-mail-thread="${x.thread_id}"><strong>${escMail(x.subject||'(no subject)')}</strong><span>${escMail(who||'')}</span><small>${escMail(preview||'No text preview')} · ${escMail(dt)}</small></button>`}).join('')}catch(e){box.innerHTML='<div class="error-box">'+escMail(e.message)+'</div>'}}

  async function openThread(id){const box=$pm('mailThread');box.innerHTML='<div class="mail-empty">Loading conversation…</div>';try{const x=await apiCall('/api/control/email/threads/'+id);const msgs=x.messages||[];box.innerHTML=`<div class="record-row"><strong>${escMail(x.thread?.subject||'Conversation')}</strong><span>${msgs.length} message${msgs.length===1?'':'s'}</span></div>${msgs.map(m=>`<article class="mail-thread-message ${escMail(m.direction)}"><div class="mail-meta"><strong>${escMail(m.direction==='inbound'?m.from:(m.to||[]).join(', '))}</strong><span>${escMail(m.created_at?new Date(m.created_at).toLocaleString():'')}</span></div><div class="mail-body">${escMail(m.text||stripHtml(m.html)||'(no text body)')}</div>${m.direction==='inbound'?`<button class="btn secondary mini" data-mail-reply="${encodeURIComponent(JSON.stringify({to:[m.from],subject:m.subject,reply_to_message_id:m.id}))}">Reply</button>`:''}</article>`).join('')}`;await loadMail()}catch(e){box.innerHTML='<div class="error-box">'+escMail(e.message)+'</div>'}}
  function stripHtml(v){const d=document.createElement('div');d.innerHTML=String(v||'');return d.textContent||''}

  function openCompose(prefill={}){mailReplyToMessageId=prefill.reply_to_message_id||null;mailDraftId=prefill.id||null;$pm('mailComposePanel').hidden=false;$pm('mailTo').value=(prefill.to||[]).join(', ');$pm('mailCc').value=(prefill.cc||[]).join(', ');$pm('mailBcc').value=(prefill.bcc||[]).join(', ');$pm('mailSubject').value=mailReplyToMessageId?replySubject(prefill.subject):prefill.subject||'';$pm('mailBody').value=prefill.text||'';$pm('mailComposeMode').textContent=mailReplyToMessageId?'Reply':(mailDraftId?'Edit draft':'New message');$pm('mailComposePanel').scrollIntoView({behavior:'smooth',block:'start'})}
  function replySubject(subject){const s=String(subject||'').trim();return /^re\s*:/i.test(s)?s:`Re: ${s}`.trim()}
  function openDraft(x){openCompose(x)}
  function closeCompose(){$pm('mailComposePanel').hidden=true;mailReplyToMessageId=null;mailDraftId=null;$pm('mailComposeMessage').textContent=''}
  function composePayload(){return {to:parseList($pm('mailTo').value),cc:parseList($pm('mailCc').value),bcc:parseList($pm('mailBcc').value),subject:$pm('mailSubject').value.trim(),text:$pm('mailBody').value,reply_to_message_id:mailReplyToMessageId}}
  async function sendMail(){const b=$pm('mailSendBtn'),m=$pm('mailComposeMessage');b.disabled=true;b.textContent='Sending…';try{const x=await apiCall('/api/control/email/send',{method:'POST',body:JSON.stringify(composePayload())});m.textContent='Sent ✓';showToast('Email Sent ✓',x.subject||'Pitmark mail sent.');setTimeout(closeCompose,450);mailFolder='sent';document.querySelectorAll('[data-mail-folder]').forEach(x=>x.classList.toggle('active',x.dataset.mailFolder==='sent'));await loadMail()}catch(e){m.textContent=e.message;showToast('Email Failed',e.message,'error')}finally{b.disabled=false;b.textContent='Send'}}
  async function saveDraft(){const b=$pm('mailDraftBtn'),m=$pm('mailComposeMessage');b.disabled=true;try{const p=composePayload();p.id=mailDraftId;delete p.reply_to_message_id;const x=await apiCall('/api/control/email/drafts',{method:'POST',body:JSON.stringify(p)});mailDraftId=x.id;m.textContent='Draft saved ✓';showToast('Draft Saved ✓',x.subject||'Draft saved.');mailFolder='drafts';await loadMail()}catch(e){m.textContent=e.message}finally{b.disabled=false}}

  function installArticleSourceBox(){const blog=document.querySelector('[data-view-section="blog"]');if(!blog||$pm('articleSourceUrl'))return;const target=$pm('bsubject')?.closest('.panel')||blog.querySelector('.panel');if(!target)return;const box=document.createElement('div');box.className='article-source-box';box.innerHTML='<div class="panel-head"><div><h3>Create Article from Source</h3><p class="muted">Paste a source and tell Pitmark what story to make from it.</p></div></div><div class="article-source-grid"><input class="input" id="articleSourceUrl" type="url" placeholder="https://source-article-url"><textarea class="textarea" id="articleSourcePrompt" rows="3" placeholder="Make our own story about this article.">Make our own story about this article.</textarea><button class="btn" id="articleSourceGenerate">Generate Article</button><span class="inline-message" id="articleSourceMessage"></span></div>';target.prepend(box);$pm('articleSourceGenerate').addEventListener('click',generateArticleFromSource)}
  async function generateArticleFromSource(){const b=$pm('articleSourceGenerate'),m=$pm('articleSourceMessage'),url=$pm('articleSourceUrl').value.trim(),prompt=$pm('articleSourcePrompt').value.trim();if(!url){m.textContent='Paste a source URL first.';return}b.disabled=true;b.textContent='Reading source…';m.textContent='Pitmark Cloud is reading and grounding the article…';try{const x=await apiCall('/api/control/content/article-from-source',{method:'POST',body:JSON.stringify({source_url:url,prompt})});$pm('btitle').value=x.title||'';$pm('bbody').value=x.body_html||'';if($pm('bsubject'))$pm('bsubject').value=x.title||prompt;if($pm('blogImagePrompt'))$pm('blogImagePrompt').value=x.image_prompt||'';m.textContent='Draft ready ✓ · Featured-image prompt grounded to the same source.';showToast('Article Draft Ready ✓','Source read and Pitmark draft generated.')}catch(e){m.textContent=e.message;showToast('Article Generation Failed',e.message,'error')}finally{b.disabled=false;b.textContent='Generate Article'}}

  function installRookieFlickerFix(){if(!window.loadRookies||window.__pitmarkRookieRefreshGuard)return;window.__pitmarkRookieRefreshGuard=true;const original=window.loadRookies;window.loadRookies=async function(){const open=document.querySelector('[data-view-section="campaigns"].active .research-detail.show');if(open)return;return original.apply(this,arguments)}}

  document.addEventListener('DOMContentLoaded',()=>{installEmailView();const originalSetView=window.setView;if(originalSetView&&!window.__pitmarkEmailSetView){window.__pitmarkEmailSetView=true;window.setView=function(name){originalSetView(name);if(name==='email')loadMail()}}if(location.hash==='#email'){setTimeout(()=>window.setView('email'),0)}});
})();
