(function(){
'use strict';

var path=location.pathname.replace(/\/+$/,'');
var match=null,type='',key='',driverSeries='',driverName='';
if((match=path.match(/^\/race-center\/driver\/([^/]+)\/(.+)$/))){
  type='driver';driverSeries=decodeURIComponent(match[1]);driverName=decodeURIComponent(match[2]);
}else if((match=path.match(/^\/race-center\/(team|track|series)\/([^/]+)$/))){
  type=match[1];key=decodeURIComponent(match[2]);
}else{return;}



var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
var api=async function(url,options){
  options=options||{};
  var headers=options.body instanceof FormData?{}:{'Content-Type':'application/json'};
  var r=await fetch(url,Object.assign({credentials:'same-origin',headers:headers},options));
  var p={};try{p=await r.json();}catch(_){}
  if(!r.ok)throw new Error(p.detail||'Race Center request failed.');
  return p;
};
var when=function(v){if(!v)return 'Date TBA';var d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(d);};
if(type==='driver'){
  key=String(driverName||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
}
var endpoint='/api/public/race-center/entity-hub/'+encodeURIComponent(type)+'/'+encodeURIComponent(key);

var root=document.createElement('section');root.className='rc-owner-hub';root.id='raceCenterOwnerHub';
var main=document.querySelector('main');if(!main)return;main.appendChild(root);
var currentHub=null;

function render(hub){
  currentHub=hub;
  var e=hub.entity||{},name=e.name||e.series_name||driverName||'Racing profile';
  var schedule=hub.schedule||[],updates=hub.updates||[],media=hub.media||[],sponsors=hub.sponsors||[],meta=hub.driver_meta||{};
  var identityBits=type==='driver'?[meta.car_number?('#'+meta.car_number):'',meta.primary_class||'',meta.team_name||e.team||'',meta.hometown||''].filter(Boolean):[];
  var scheduleHtml=schedule.length?schedule.map(function(x){return '<div class="rc-owner-event" data-schedule-id="'+String(x.id)+'"><time>'+esc(when(x.start_at))+'</time><div><strong>'+esc(x.title||e.name||'Race event')+'</strong><small>'+esc([x.venue,x.location,x.class_name].filter(Boolean).join(' · '))+'</small>'+(x.flyer_url?'<a href="'+esc(x.flyer_url)+'" target="_blank" rel="noopener" class="rc-owner-flyer">View flyer ↗</a>':'')+'</div><span class="rc-owner-status '+esc(x.status)+'">'+esc(x.status||'scheduled')+(hub.can_manage?'<br><button type="button" class="button rc-edit-race" data-id="'+String(x.id)+'">Edit</button> <button type="button" class="button rc-delete-race" data-id="'+String(x.id)+'">Remove</button>':'')+'</span></div>';}).join(''):'<div class="rc-owner-empty">No owner-managed races have been added yet.</div>';
  var updatesHtml=updates.length?updates.map(function(x){return '<article class="rc-owner-update"><p>'+esc(x.body)+'</p>'+(x.media_url?'<img src="'+esc(x.media_url)+'" alt="">':'')+'<time>'+esc(when(x.created_at))+'</time></article>';}).join(''):'<div class="rc-owner-empty">No trackside updates yet.</div>';
  var mediaHtml=media.length?media.map(function(x){return '<figure><img src="'+esc(x.url)+'" alt="'+esc(x.alt_text||x.title||name)+'" loading="lazy"><figcaption>'+esc(x.title||x.kind)+(x.credit?' · '+esc(x.credit):'')+'</figcaption></figure>';}).join(''):'<div class="rc-owner-empty">No photos or flyers uploaded yet.</div>';
  var sponsorHtml=sponsors.length?sponsors.map(function(x){var tag=x.website_url?'a':'div';return '<'+tag+' class="rc-owner-sponsor"'+(x.website_url?' href="'+esc(x.website_url)+'" target="_blank" rel="noopener"':'')+'>'+(x.logo_url?'<img src="'+esc(x.logo_url)+'" alt="'+esc(x.name)+'">':'')+'<strong>'+esc(x.name)+'</strong>'+(x.description?'<small>'+esc(x.description)+'</small>':'')+'</'+tag+'>';}).join(''):'<div class="rc-owner-empty">No sponsors listed yet.</div>';
  root.innerHTML='<div class="section-head"><div><span class="eyebrow">RACING HOME</span><h2>'+esc(name)+'</h2>'+(identityBits.length?'<p class="rc-owner-meta">'+esc(identityBits.join(' · '))+'</p>':'')+'</div>'+(hub.can_manage?'<span class="rc-owner-badge">Verified owner controls</span>':'')+'</div><div class="rc-owner-grid"><div><section class="rc-owner-card"><header><div><span class="eyebrow">SEASON SCHEDULE</span><h3>Where '+esc(name)+' races next</h3></div><p>Owner-managed schedule</p></header><div class="rc-owner-body rc-owner-schedule">'+scheduleHtml+'</div></section><section class="rc-owner-card rc-space"><header><div><span class="eyebrow">TRACKSIDE UPDATES</span><h3>From the racer</h3></div></header><div class="rc-owner-body rc-owner-updates">'+updatesHtml+'</div></section></div><div><section class="rc-owner-card"><header><div><span class="eyebrow">MEDIA</span><h3>Photos + flyers</h3></div></header><div class="rc-owner-body rc-owner-media">'+mediaHtml+'</div></section><section class="rc-owner-card rc-space"><header><div><span class="eyebrow">SPONSORS</span><h3>Partners</h3></div></header><div class="rc-owner-body rc-owner-sponsors">'+sponsorHtml+'</div></section></div></div>'+(hub.can_manage?manageHtml():'');
  if(hub.can_manage)bindManage();
}
function manageHtml(){
  var m=(currentHub&&currentHub.driver_meta)||{};
  var driverForm=type==='driver'?'<form class="rc-owner-form" id="rcDriverMetaForm"><h3>Driver identity</h3><label>Hometown<input name="hometown" value="'+esc(m.hometown||'')+'"></label><label>Car number<input name="car_number" value="'+esc(m.car_number||'')+'"></label><label>Primary class<input name="primary_class" value="'+esc(m.primary_class||'')+'"></label><label>Other classes, comma separated<input name="classes" value="'+esc((m.classes||[]).join(', '))+'"></label><label>Team<input name="team_name" value="'+esc(m.team_name||'')+'"></label><label>Car / program info<textarea name="car_info">'+esc(m.car_info||'')+'</textarea></label><label>Website<input name="website_url" type="url" value="'+esc(m.website_url||'')+'"></label><label>Social links, one per line<textarea name="social_links" placeholder="Facebook | https://...">'+esc((m.social_links||[]).map(function(x){return (x.label||'Link')+' | '+(x.url||'');}).join('\n'))+'</textarea></label><button class="button primary" type="submit">Save driver profile</button><div class="rc-owner-message"></div></form>':'';
  return '<section class="rc-owner-manage"><header><span class="eyebrow">MANAGE YOUR RACING HOME</span><h2>Update this profile from the track</h2></header><div class="rc-owner-manage-grid">'+driverForm+'<form class="rc-owner-form" id="rcScheduleForm"><input type="hidden" name="item_id"><h3 id="rcScheduleHeading">Add race</h3><label>Event<input name="title" required placeholder="Race or event name"></label><label>Date + time<input name="start_at" type="datetime-local"></label><label>Track<input name="venue" placeholder="Track"></label><label>Location<input name="location" placeholder="City, State"></label><label>Class<input name="class_name" placeholder="Class / division"></label><label>Status<select name="status"><option>scheduled</option><option>postponed</option><option>canceled</option><option>completed</option></select></label><label>Event link<input name="event_url" type="url" placeholder="https://"></label><label>Notes<textarea name="notes"></textarea></label><label>Flyer<input name="flyer" type="file" accept="image/*"></label><button class="button primary" id="rcScheduleSave" type="submit">Add to schedule</button><button class="button rc-owner-cancel" id="rcScheduleCancel" type="button" hidden>Cancel edit</button><div class="rc-owner-message"></div></form><form class="rc-owner-form" id="rcUpdateForm"><h3>Post race update</h3><label>Update<textarea name="body" required maxlength="1200" placeholder="Race week, result, sponsor thanks, car update…"></textarea></label><label>Photo<input name="photo" type="file" accept="image/*"></label><button class="button primary" type="submit">Post update</button><div class="rc-owner-message"></div></form><form class="rc-owner-form" id="rcMediaForm"><h3>Add photo or flyer</h3><label>Image<input name="image" type="file" accept="image/*" required></label><label>Type<select name="media_kind"><option value="photo">Photo</option><option value="flyer">Flyer</option></select></label><label>Title<input name="title"></label><label>Photo credit<input name="credit"></label><button class="button primary" type="submit">Upload media</button><div class="rc-owner-message"></div></form><form class="rc-owner-form" id="rcSponsorForm"><h3>Update sponsors</h3><label>One sponsor per line<textarea name="sponsors" placeholder="Sponsor Name | https://website.com | https://logo-url | Optional note"></textarea></label><button class="button primary" type="submit">Save sponsors</button><div class="rc-owner-message"></div></form></div></section>';
}
async function upload(file,kind,title,credit){
  if(!file)return null;var fd=new FormData();fd.append('image',file);fd.append('media_kind',kind||'photo');fd.append('title',title||'');fd.append('credit',credit||'');fd.append('alt_text',title||'');
  var base='/api/public/race-center/entity-hub/'+encodeURIComponent(type)+'/'+encodeURIComponent(key);
  var p=await api(base+'/media',{method:'POST',body:fd});return p.media||null;
}
function bindManage(){
  document.querySelector('#rcScheduleForm').addEventListener('submit',async function(ev){ev.preventDefault();var form=ev.currentTarget,msg=form.querySelector('.rc-owner-message');msg.textContent='Saving…';try{var d=new FormData(form),id=String(d.get('item_id')||''),existing=id&&currentHub?(currentHub.schedule||[]).find(function(x){return String(x.id)===id;}):null,m=await upload(d.get('flyer'),'flyer',d.get('title'),'');var payload={title:d.get('title'),start_at:d.get('start_at'),venue:d.get('venue'),location:d.get('location'),class_name:d.get('class_name'),event_url:d.get('event_url'),status:d.get('status'),notes:d.get('notes'),flyer_media_id:(m&&m.id)||(existing&&existing.flyer_media_id)||null};await api(actionBase()+'/schedule'+(id?'/'+encodeURIComponent(id):''),{method:id?'PUT':'POST',body:JSON.stringify(payload)});await refresh();}catch(e){msg.textContent=e.message;}});
  document.querySelectorAll('.rc-edit-race').forEach(function(btn){btn.addEventListener('click',function(){var id=String(btn.dataset.id||''),x=(currentHub.schedule||[]).find(function(row){return String(row.id)===id;});if(!x)return;var form=document.querySelector('#rcScheduleForm');form.elements.item_id.value=id;form.elements.title.value=x.title||'';form.elements.start_at.value=String(x.start_at||'').slice(0,16);form.elements.venue.value=x.venue||'';form.elements.location.value=x.location||'';form.elements.class_name.value=x.class_name||'';form.elements.event_url.value=x.event_url||'';form.elements.status.value=x.status||'scheduled';form.elements.notes.value=x.notes||'';document.querySelector('#rcScheduleHeading').textContent='Edit race';document.querySelector('#rcScheduleSave').textContent='Save changes';document.querySelector('#rcScheduleCancel').hidden=false;form.scrollIntoView({behavior:'smooth',block:'center'});});});
  document.querySelectorAll('.rc-delete-race').forEach(function(btn){btn.addEventListener('click',async function(){btn.disabled=true;try{await api(actionBase()+'/schedule/'+encodeURIComponent(btn.dataset.id),{method:'DELETE'});await refresh();}catch(e){btn.disabled=false;}});});
  document.querySelector('#rcScheduleCancel').addEventListener('click',function(){var form=document.querySelector('#rcScheduleForm');form.reset();form.elements.item_id.value='';document.querySelector('#rcScheduleHeading').textContent='Add race';document.querySelector('#rcScheduleSave').textContent='Add to schedule';this.hidden=true;});
  if(type==='driver')document.querySelector('#rcDriverMetaForm').addEventListener('submit',async function(ev){ev.preventDefault();var form=ev.currentTarget,msg=form.querySelector('.rc-owner-message');msg.textContent='Saving…';try{var d=new FormData(form),social=String(d.get('social_links')||'').split(/\n+/).map(function(line){var p=line.split('|').map(function(x){return x.trim();});return {label:p[0]||'Link',url:p[1]||''};}).filter(function(x){return x.url;});var payload={hometown:d.get('hometown'),car_number:d.get('car_number'),primary_class:d.get('primary_class'),classes:String(d.get('classes')||'').split(',').map(function(x){return x.trim();}).filter(Boolean),team_name:d.get('team_name'),car_info:d.get('car_info'),website_url:d.get('website_url'),social_links:social};await api('/api/public/race-center/entity-hub/driver/'+encodeURIComponent(key)+'/driver-meta',{method:'PUT',body:JSON.stringify(payload)});await refresh();}catch(e){msg.textContent=e.message;}});
  document.querySelector('#rcUpdateForm').addEventListener('submit',async function(ev){ev.preventDefault();var form=ev.currentTarget,msg=form.querySelector('.rc-owner-message');msg.textContent='Posting…';try{var d=new FormData(form),m=await upload(d.get('photo'),'photo','Race update','');await api(actionBase()+'/updates',{method:'POST',body:JSON.stringify({body:d.get('body'),media_id:m&&m.id})});await refresh();}catch(e){msg.textContent=e.message;}});
  document.querySelector('#rcMediaForm').addEventListener('submit',async function(ev){ev.preventDefault();var form=ev.currentTarget,msg=form.querySelector('.rc-owner-message');msg.textContent='Uploading…';try{var d=new FormData(form);await upload(d.get('image'),d.get('media_kind'),d.get('title'),d.get('credit'));await refresh();}catch(e){msg.textContent=e.message;}});
  document.querySelector('#rcSponsorForm').addEventListener('submit',async function(ev){ev.preventDefault();var form=ev.currentTarget,msg=form.querySelector('.rc-owner-message');msg.textContent='Saving…';try{var d=new FormData(form),rows=String(d.get('sponsors')||'').split(/\n+/).map(function(line,i){var p=line.split('|').map(function(x){return x.trim();});return {name:p[0]||'',website_url:p[1]||'',logo_url:p[2]||'',description:p[3]||'',sort_order:i};}).filter(function(x){return x.name;});await api(actionBase()+'/sponsors',{method:'PUT',body:JSON.stringify({sponsors:rows})});await refresh();}catch(e){msg.textContent=e.message;}});
}
function actionBase(){return '/api/public/race-center/entity-hub/'+encodeURIComponent(type)+'/'+encodeURIComponent(key);}
async function refresh(){var h=await api(endpoint);render(h);}
refresh().catch(function(e){root.innerHTML='<div class="rc-owner-empty">'+esc(e.message)+'</div>';});
})();